import {rng} from './random.js';
import {searchAssets} from './library.js';
import {catalogSearch,catalogEntry} from './asset-catalog.js';
export const BENNINGTON={id:'bennington',name:'Bennington, Vermont',currency:'USD',language:'en',referencePopulation:14953,censusYear:2025,demographics:{under5:.035,under18:.177,over65:.252,female:.514},source:'https://www.census.gov/quickfacts/fact/table/benningtontownbenningtoncountyvermont/RHI125224',note:'Synthetic residents in a stylized, researched town. Streets and selected public institutions are real; private businesses, households and stories are fictional. Age-cohort targets use Census QuickFacts; race and Hispanic ethnicity are overlapping census dimensions, not interchangeable skin labels.'};
const quarters=[['Downtown','Main Street','shops, civic life and chance encounters'],['Silver Street Gardens','Silver Street','families, gardens and library visits'],['Old Bennington','Monument Avenue','historic houses, quiet walks and intergenerational neighbors'],['North Bennington','Main Street, North Bennington','village homes and community gatherings'],['College Hill','College Drive','students, arts, research and shared projects'],['Benmont Riverside','Benmont Avenue','workshops, apartments and mutual practical help'],['East Main','East Main Street','mixed housing, services and everyday errands'],['South Street','South Street','family homes, care and neighborhood routines'],['Northside','Northside Drive','shops, workplaces and varied household budgets']];
const given={female:['Abigail','Alice','Amelia','Audrey','Avery','Charlotte','Claire','Eleanor','Elizabeth','Emma','Evelyn','Fiona','Grace','Harper','Hazel','Isabel','Jane','Julia','Katherine','Leah','Lily','Lucy','Maya','Nora','Olivia','Penelope','Rose','Ruby','Sarah','Sophie','Violet','Zoe'],male:['Adam','Andrew','Benjamin','Caleb','Charles','Daniel','David','Eli','Ethan','Finn','George','Henry','Isaac','Jack','James','Jonah','Joseph','Julian','Leo','Liam','Lucas','Miles','Nathan','Noah','Oliver','Owen','Samuel','Theo','Thomas','William']};
const lastNames=['Adams','Allen','Baker','Bennett','Brooks','Brown','Campbell','Carter','Clark','Collins','Davis','Edwards','Evans','Foster','Gray','Green','Hall','Harris','Hayes','Hill','Hughes','Johnson','Kelly','King','Lee','Lewis','Martin','Miller','Mitchell','Moore','Morgan','Nelson','Parker','Reed','Rivera','Roberts','Scott','Smith','Stone','Taylor','Thompson','Turner','Walker','Ward','Watson','White','Williams','Wilson','Wood','Young'];
export function benningtonHouseholds(population,seed){
 const r=rng(seed+':bennington-demography'),groups=[],kids=Math.round(population*.177),small=Math.min(kids,Math.round(population*.035));let adults=population-kids-Math.round(population*.252),older=population-kids-adults,remaining=kids,young=small;
 while(remaining>0&&adults>0){const n=Math.min(remaining,r()<.55?2:1),ages=[];for(let k=0;k<n;k++){ages.push(young>0?(young--,Math.floor(r()*5)):5+Math.floor(r()*13));}const parentAge=Math.max(26+Math.floor(r()*27),Math.max(...ages)+20),parents=Math.min(adults,r()<.28?1:2);groups.push({ages:[parentAge,...(parents>1?[Math.min(64,parentAge+2)]:[]),...ages],parents});adults-=parents;remaining-=n;}
 while(older>0){const n=Math.min(older,r()<.5?1:2),age=65+Math.floor(r()*25);groups.push({ages:[age,...(n===2?[Math.min(95,age+2)]:[])],parents:n});older-=n;}
 while(adults>0){const n=Math.min(adults,r()<.38?1:2),age=18+Math.floor(r()*47);groups.push({ages:[age,...(n===2?[Math.min(64,age+Math.floor(r()*5))]:[])],parents:n,partners:n===2?r()>.14:false});adults-=n;}
 // Interleave generations geographically instead of putting every senior on one street.
 for(let i=groups.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[groups[i],groups[j]]=[groups[j],groups[i]];}return groups;
}
export function benningtonName(gender,index,household,seed){const r=rng(seed+':name:'+index);return given[gender][Math.floor(r()*given[gender].length)]+' '+lastNames[household%lastNames.length];}
export function benningtonHeritage(index,seed){const n=rng(seed+':heritage:'+index)();return n<.891?'white':n<.922?'latino':n<.934?'black':n<.949?(index%2?'japanese':'indian'):n<.951?'indigenous_american':['white','black','latino','southeast_asian','arab'][index%5];}
// Distinct establishing pictures for each neighborhood. Captions describe
// reusable illustrative art, not photographs of the actual Bennington streets.
export function assignNeighborhoodArtwork(places){
 // These establishing views were visually checked: exterior views, distinct
 // compositions, no shop interiors accidentally matched through 'street grid'.
 const reviewed=['hfb-base-083-v1','hfb-bg-supp-0343','hfb-bg-supp-0395','hfb-bg-city-0125','hfb-bg-supp-0145','hfb-bg-drama-0092','hfb-bg-city-0290','hfb-bg-city-0132','hfb-bg-city-0214','hfb-base-083-v2','hfb-bg-supp-0347','hfb-bg-city-0154','hfb-base-088-v1','hfb-bg-supp-0153','hfb-bg-drama-0091','hfb-bg-city-0398','hfb-bg-city-0128','hfb-base-083-v3','hfb-bg-supp-0158','hfb-bg-supp-0146','hfb-bg-drama-0104'];
 const used=new Set(),queries=[
  'main street storefronts diner brick town', 'suburban street houses lawns maple gardens',
  'historic clapboard houses village green', 'village main street farming town',
  'red brick university quadrangle college lawn', 'riverside park brick workshops',
  'neighborhood high street shops sidewalk', 'residential houses porch trees',
  'retail neighborhood boulevard storefronts'
 ];
 const fallback=catalogSearch('street residential park courtyard exterior',{kind:'background',limit:50});
 let i=0;
 for(const p of places.filter(p=>p.kind==='neighborhood')){
  const preferred=reviewed[i]?catalogEntry(reviewed[i]):null,q=queries[i++%queries.length],all=[...catalogSearch(q,{kind:'background',limit:50}),...fallback];
  const suitable=all.filter(a=>{
   const text=a.caption.en.toLowerCase();
   const subject=text.split('.')[0],scale=a.metadata?.variant_axes?.find(v=>v.axis==='scale')?.value||'';
   return !/interior/.test(scale)&&/street|exterior|quadrangle|plaza|village green|park|boulevard|promenade|campus|courtyard/.test(subject)&&!/medieval|desert|japan|asian|european|scandinavian|mediterranean|canal|coastal|seaside|hitching|feed store|arcade|interior|indoor|bedroom|classroom|lecture|auditorium|corridor|room|horror|ruined|abandoned|snow/.test(text);
  });
  const chosen=preferred&&!used.has(preferred.id)?preferred:suitable.find(a=>!used.has(a.id))||searchAssets(q).find(a=>!used.has(a.id));
  if(chosen){p.asset_id=chosen.id;used.add(chosen.id);}
 }
}
export function localizeBennington(places,edges,people,identities,worldId){
 const neighborhoods=places.filter(p=>p.kind==='neighborhood'),byId=new Map(places.map(p=>[p.id,p]));
 for(let i=0;i<neighborhoods.length;i++){const p=neighborhoods[i],[base,street,character]=quarters[i%quarters.length],block=Math.floor(i/quarters.length);p.name=base+(block?' · '+['North','East','South','West'][((block-1)%4)]+' block '+block:'');p.purpose='Vermont New England residential street autumn '+character;identities[p.id]={name:p.name,street,district:base,character,ritual:'Neighbors meet after work for a walk, a shared hobby or practical help.',meetingPurpose:i%2?'town park':'public library',theme:i%2?'walking':'reading'};}
 let d=0;for(const p of places)if(p.kind==='district')p.name=['Central Bennington','Northern villages & college','Southern neighborhoods','Foothills & riverside'][d++%4];else if(p.kind==='country')p.name='United States';else if(p.kind==='city')p.name='Bennington, Vermont';
 const names={school:'Bennington Community School',daycare:'Maple Sprout Early Learning',campus:'Bennington College',library:'Bennington Free Library',townhall:'Bennington Town Offices',clinic:'South Valley Medical Center',fire:'Bennington Fire Department',park:'Willowbank Community Park',cafe:'Blue Birch Diner & Market'};
 for(const [key,name] of Object.entries(names)){const b=byId.get(worldId+'_l_'+key);if(b){b.name=name;const oldParent=b.parent_id;b.parent_id=neighborhoods[(key==='campus'?4:key==='library'?1:0)%neighborhoods.length].id;for(const e of edges){if(e.from_id===oldParent&&e.to_id===b.id)e.from_id=b.parent_id;if(e.to_id===oldParent&&e.from_id===b.id)e.to_id=b.parent_id;}for(const room of places.filter(p=>p.parent_id===b.id))room.name=name+' · '+(/Hauptraum/.test(room.name)?'main room':room.name.split(' · ').at(-1));}}
 const labels={...{"Klassenraum A": "Classroom A", "Klassenraum B": "Classroom B", "Schulflur": "School hallway", "Schulmensa": "School cafeteria", "Garderobe & Flur": "Coatroom & hallway", "Spielzimmer": "Playroom", "Kinderküche": "Children’s dining room", "Spielgarten": "Play garden", "Forschungslabor": "Research laboratory", "Institutsflur": "Institute hallway", "Seminarraum": "Seminar room", "Arbeitsbibliothek": "Research library", "Campusmensa": "College dining hall", "Ausleihe & Lesesaal": "Loans & reading room", "Bibliotheksfoyer": "Library foyer", "Stiller Leseraum": "Quiet reading room", "Lernraum": "Study room", "Kinderbibliothek": "Children’s library", "Bürgerbüro": "Public service desk", "Rathausfoyer": "Town offices lobby", "Sitzungsraum": "Meeting room", "Verwaltung": "Administration", "Personalraum": "Staff room", "Behandlungszimmer": "Treatment room", "Wartebereich": "Waiting area", "Sprechzimmer": "Consultation room", "Praxisbüro": "Medical office", "Werkstatt": "Workshop", "Wachflur": "Station hallway", "Fahrzeughalle": "Vehicle bay", "Schulungsraum": "Training room", "Gemeinschaftsküche": "Shared kitchen", "Gastraum": "Dining room", "Ladenpassage": "Shopping passage", "Backstube": "Bakery kitchen", "Nachbarschaftsladen": "Neighborhood shop", "Caféterrasse": "Cafe terrace", "Parkwiese": "Park lawn", "Parkwege": "Park paths", "Spielplatz": "Playground", "Gemeinschaftsgarten": "Community garden", "Picknickplatz": "Picnic area", "Toiletten": "Restrooms"},'Wohnzimmer':'Living room','Küche':'Kitchen','Bad':'Bathroom','Schlafzimmer':'Bedroom','Haupteingang':'Entrance','Haupthalle':'Main hall','Flur':'Hallway','Klassenzimmer':'Classroom','Lehrerzimmer':'Staff room','Schulhof':'Schoolyard','Mensa':'Dining hall','Lesesaal':'Reading room','Labor':'Laboratory','Gruppenraum':'Group room','Büro':'Office','Garten':'Garden'};
 for(const p of places){p.name=p.name.split(' · ').map(part=>labels[part]||part).join(' · ');if(p.kind==='street')p.name=identities[p.parent_id]?.street||p.name;p.name=p.name.replace(/Haus (\d+)/g,'House $1');if(/family house/.test(p.purpose)){const n=identities[p.parent_id];p.name=(n?.street||'Main Street')+' · Home '+p.id.split('_home').at(-1);p.purpose='New England Vermont clapboard family house residential exterior porch autumn';const candidates=searchAssets(p.purpose);p.asset_id=candidates[Math.floor(rng(p.id)()*candidates.length)]?.id||p.asset_id;}}
 for(const p of people){let at=byId.get(p.household_id);while(at&&!identities[at.id])at=byId.get(at.parent_id);if(at)p.profile.neighborhood={id:at.id,...identities[at.id]};}
 const add=(key,name,purpose,rooms,quarter=0)=>{const parent=neighborhoods[quarter%neighborhoods.length],id=worldId+'_l_bn_'+key,b={id,world_id:worldId,parent_id:parent.id,name,kind:'building',purpose,asset_id:searchAssets(purpose)[0]?.id||null,x:100,y:100,capacity:100,anchored:0,landmark:1,affordances:[]};places.push(b);edges.push({from_id:parent.id,to_id:id,seconds:180},{from_id:id,to_id:parent.id,seconds:180});for(const [i,[label,desc,affordances]] of rooms.entries()){const rid=id+'_'+i;places.push({...b,id:rid,parent_id:id,name:label,kind:'room',purpose:desc,asset_id:searchAssets(desc)[0]?.id||null,landmark:0,affordances,capacity:30});edges.push({from_id:id,to_id:rid,seconds:60},{from_id:rid,to_id:id,seconds:60});}return id;};
 add('church','Old First Church','New England white wooden church',[['Meeting room','church meeting hall community chairs',['table','bookshelf','bench']],['Quiet garden','church garden peaceful trees',['bench','planter']]],2);
 add('monument','Bennington Battle Monument','Vermont stone obelisk monument park',[['Monument grounds','stone monument public park trees',['park_marker','bench']]],2);
 add('arts','Bennington College · VAPA','college visual performing arts building',[['Arts studio','university art studio painting drawing',['desk','table']],['Rehearsal room','music rehearsal room university',['desk','table']],['Student lounge','college student lounge sofa books',['sofa','bookshelf','table']]],4);
 add('crossett','Bennington College · Crossett Library','college library exterior',[['Study room','university library quiet study desks',['bookshelf','desk']],['Seminar room','college seminar room classroom',['desk','table']]],4);
 add('mystery','Alder Hollow House · fictional','secluded New England old house forest dusk mystery',[['Private study','old study room books desk mysterious scientific instruments',['desk','bookshelf']],['Overgrown garden','abandoned garden twilight forest',['bench','planter']]],8);
 assignNeighborhoodArtwork(places);
 return BENNINGTON;
}
