// Display text only; upstream action identifiers and mechanics remain unchanged.
const activities={eat:['prepares a meal','A proper meal would do me good.'],drink:['has a drink','Time for a glass of water.'],toilet:['uses the bathroom','I’ll take care of this need first.'],shower:['takes a shower','A warm shower would feel good.'],sleep:['sleeps','I need some rest.'],relax:['takes a quiet break','A quiet moment would be nice.'],read:['reads a book','I’d like to read another chapter.'],garden:['tends the plants','I’d like to take care of the plants.'],work:['works on a task','I’d like to make progress at work.'],stroll:['goes for a walk','A short walk would do me good.'],wait:['waits a moment','I’ll wait a moment and think about what to do next.'],creative_hobby:['works on a creative project','I’d like to make something of my own.'],school_day:['attends class','I’d like to learn and see my classmates.'],kindergarten_day:['plays and learns at preschool','I’d like to play with the other children.'],community_meet:['attends a neighborhood gathering','I’d like to get to know my neighbors better.']};
const leisure={host_party:'hosts a gathering',attend_party:'attends a gathering',ask_on_date:'asks someone on a date',go_on_date:'goes on a date',dance:'dances',karaoke:'sings karaoke',board_games:'plays a board game',video_games:'plays a video game',read_for_fun:'reads for pleasure',write_story:'writes a story',paint:'paints',play_instrument:'plays an instrument',craft_project:'works on a craft project',garden:'gardens',cook_for_fun:'cooks for fun',bake_treats:'bakes a treat',go_for_walk:'goes for a walk',hike:'goes hiking',jog:'jogs',work_out:'works out',play_team_sport:'plays a team sport',swim:'swims',visit_museum:'visits a museum',see_live_music:'listens to live music',watch_movie:'watches a movie',volunteer:'volunteers',shop_for_fun:'browses the shops',relax_at_home:'relaxes at home',meditate:'meditates',make_friends:'makes new friends'};
const marketActivities={walk:'goes for a walk or jog',park_play:'plays in the park',library:'visits the library or a reading group',garden:'spends time in the community garden',home_game:'joins a game night at home',home_meal:'has a meal at home',invite_dinner:'invites someone to dinner',coffee:'meets for coffee or a café conversation',cafe_food:'has a meal at a café',takeaway:'gets takeaway food',restaurant:'goes out for dinner',swim:'goes swimming',cinema:'goes to the cinema',gym_dropin:'visits the gym',sports_club:'takes part in a sports club',music_lesson:'takes a music lesson',museum:'visits a museum or exhibition',concert:'goes to a concert',craft:'works on a creative hobby',gaming:'plays games at home',bike:'goes for a bike ride',bus:'takes the bus',car_trip:'takes a car trip',weekend_trip:'goes on a weekend trip',charity:'helps out in the neighborhood',course:'takes a training course',haircut:'gets a haircut',birthday:'celebrates a birthday',repair_service:'arranges a repair',therapy:'attends an advice or counseling session'};
const marketPlans={walk:'a walk or jog',park_play:'some playtime in the park',library:'a library visit or reading group',garden:'time in the community garden',home_game:'a game night at home',home_meal:'a meal at home',invite_dinner:'dinner with a guest',coffee:'coffee or a café conversation',cafe_food:'a meal at a café',takeaway:'takeaway food',restaurant:'dinner out',swim:'a swim',cinema:'a trip to the cinema',gym_dropin:'a gym visit',sports_club:'a sports club session',music_lesson:'a music lesson',museum:'a museum or exhibition visit',concert:'a concert',craft:'a creative hobby',gaming:'some gaming at home',bike:'a bike ride',bus:'a bus ride',car_trip:'a car trip',weekend_trip:'a weekend trip',charity:'neighborhood volunteering',course:'a training course',haircut:'a haircut',birthday:'a birthday celebration',repair_service:'a repair appointment',therapy:'an advice or counseling appointment'};
const expandedActivities={elder_care:'supports a family member with everyday needs',study:'studies for a course or vocational program',obligation:'works on an accepted everyday task',holiday_work:'works a safe holiday job',training:'practices a skill for a personal goal',item_use:'uses a special belonging',infant_care:'cares for a young child',supported_care:'attends an agreed support appointment'};
const expandedThoughts={elder_care:'I’ll make time to support someone in my family.',study:'I’d like to make progress in my studies or training.',obligation:'I’ll work on the everyday task I accepted.',holiday_work:'I’ll do my safe holiday job.',training:'I’d like to practice a skill that matters to my goal.',item_use:'I’d like to spend time with something I value.',infant_care:'I’ll take care of the young child.',supported_care:'I’ll attend the support appointment we agreed on.'};
function catalogActivity(kind){
  const market=kind?.match(/^leisure_market_(.+)$/)?.[1];
  if(market&&marketActivities[market])return marketActivities[market];
  const expanded=kind?.match(/^leisure_expanded_(.+)$/)?.[1];
  if(expanded&&expandedActivities[expanded])return expandedActivities[expanded];
  return null;
}
export function activity(kind,catalog){return activities[kind]?.[0] || leisure[kind?.replace(/^leisure_/,'')] || catalogActivity(kind) || kind;}
export function thought(kind,catalog){
  const expanded=kind?.match(/^leisure_expanded_(.+)$/)?.[1];
  const market=kind?.match(/^leisure_market_(.+)$/)?.[1];
  return activities[kind]?.[1] || (leisure[kind?.replace(/^leisure_/,'')]?'I’d like to do this: '+leisure[kind.replace(/^leisure_/,'')]+'.':expandedThoughts[expanded] || (marketPlans[market]?'I’d like to make time for '+marketPlans[market]+'.':'I take a moment to get my bearings.'));
}
// A traveller is between nodes; maps and scenes use the last reached node as
// a visual reference and keep the actual location null in simulation state.
export function currentPlaceId(sim,state){
  return sim.location_id||((state?.route?.index>0)?state.route.path?.[state.route.index-1]?.id:state?.route?.from)||null;
}
