// Presentation guidance, not permission to add uncommitted simulation events.
// Allow enough alternating beats to show the initiating action and its outcome.
export const MAX_FLASHBACK_LINES=12;
export const SCENE_WRITING_INSTRUCTIONS=`PLAYABLE SCENES, NOT CRYPTIC AFTERMATH:
Plausible NSFW and adult topics are explicitly allowed when grounded in the characters and recorded events: adult attraction, consensual intimacy, infidelity, jealousy, strong language, addiction, illness, crime and difficult relationship conflicts. Do not impose a blanket family-friendly tone or hide mature events behind vague euphemisms. State what happened clearly, with emotional and practical consequences; keep intimate depictions non-graphic and avoid gratuitous gore. This permission never overrides the age, consent, privacy or factual-evidence rules below.
For every character anchor with a meaningful event during the time jump, let the player understand what actually happened. Write a compact screenplay in the playable narration arrays, not only in story, thoughts or storytellerNotes. Each displayed scene may use 200–300 words when needed; shorter is welcome when the event is simple. This is a per-scene allowance, not a minimum or a quota to fill. Each line should carry an action, useful dialogue or a consequence; avoid padding and repeated introspection.
Establish when and where the scene takes place, who is there and what starts the encounter. Show the initiating action or request explicitly, the other person's response, what each person then does, and the concrete outcome. Alternate narrator action beats with character speech and, sparingly, inner thought. Use names and specific verbs; make it clear who said or did what to whom. When a Sim is alone, clear narrated actions and a brief thought are enough. Use up to ${MAX_FLASHBACK_LINES} beats per flashback, normally 5–10 when an exchange needs room. Put narrator action descriptions in speaker:narrator, mode:speech; character dialogue uses that Sim's exact ID and mode:speech. Do not embed an entire multi-speaker conversation inside a narrator line.
Show the cause BEFORE describing its emotional or practical consequence. Do not replace an encounter with phrases such as "after what happened", "she sought distraction", "they crossed a boundary" or "everything felt different" without saying what the encounter involved. If someone refuses an invitation, include the actual invitation and the refusal, then show whether it is respected. Make every material change you narrate understandable: what happened, the supported outcome, and why it matters now. Do not list every routine minute or recite numeric stats. The present scene can briefly connect to an earlier turning point but should not repeat the whole flashback.
Ground scenes in the supplied event facts and outcomes. For a recorded exchange, you may give the dialogue concrete wording and describe modest gestures consistent with its category, context, consent and outcome. Those are narrative rendering of the recorded encounter, not new physical or relationship events. Do not invent a consequential confession, accusation, diagnosis, treatment, injury, purchase, intimate encounter or agreement merely to make the scene specific. Structured facts take precedence over a generic description: if facts.outcome is declined, the activity was proposed but did NOT take place, even if a template says the Sims "play together". A proposed topic is not proof that an allegation is true or that it was discussed. Retrieve relevant event/journal evidence when necessary; if the record remains underspecified, state the limited known action plainly instead of hinting at an unspecified dramatic incident. Private feelings remain private unless actually voiced; distinguish suspicions from facts.
For jumps of at least one hour, use flashbacks for meaningful earlier events, following flashbackPlan.maxPerAnchor, and narration for the final five minutes at current locations. Keep the episode summary chronological and cover other important recorded changes that do not need their own scene. Shared encounters need not be repeated for each anchor. Before returning, check that the player can answer "What did they actually do or say, how did the other person respond, and what changed?" for each dramatized turning point.`;
