import {Worker,isMainThread} from 'node:worker_threads';import os from 'node:os';
import {db} from './schema.js';import {busy} from './engine.js';import {uid} from '../db.js';
// Runtime jobs are installation state, not part of portable world history.
db.exec(`CREATE TABLE IF NOT EXISTS living_turbo_jobs(id TEXT PRIMARY KEY,world_id TEXT NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,user_id TEXT NOT NULL,status TEXT NOT NULL,minutes INTEGER NOT NULL,completed INTEGER NOT NULL DEFAULT 0,start_seconds INTEGER NOT NULL,started_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,error TEXT,metrics TEXT);CREATE INDEX IF NOT EXISTS living_turbo_world ON living_turbo_jobs(world_id,started_at);`);
const workers=new Map(),capacity=Math.max(1,Math.min(2,os.availableParallelism()-1));
// Restart never silently resumes a year of compute. The saved world clock is authoritative.
if(isMainThread)for(const job of db.prepare("SELECT * FROM living_turbo_jobs WHERE status IN ('running','cancelling')").all()){const clock=db.prepare('SELECT seconds FROM lw_worlds WHERE world_id=?').get(job.world_id);db.prepare("UPDATE living_turbo_jobs SET status='interrupted',completed=?,error=?,updated_at=? WHERE id=?").run(Math.max(0,Math.floor(((clock?.seconds||job.start_seconds)-job.start_seconds)/60)),'Server restarted; completed checkpoints remain saved.',Date.now(),job.id);}
export function turboStatus(worldId){const j=db.prepare('SELECT * FROM living_turbo_jobs WHERE world_id=? ORDER BY started_at DESC LIMIT 1').get(worldId);if(!j)return null;const elapsedMs=(["running","cancelling"].includes(j.status)?Date.now():j.updated_at)-j.started_at,remaining=j.minutes-j.completed;return {...j,elapsedMs,estimatedRemainingMs:j.completed>=60&&j.status==='running'?Math.round(elapsedMs/j.completed*remaining):null,metrics:j.metrics?JSON.parse(j.metrics):null,workerCapacity:capacity};}
export function startTurbo(user,worldId,minutes){
 if(!Number.isInteger(minutes)||minutes<1||minutes>525600)throw Object.assign(new Error('Choose from one minute to 365 days.'),{statusCode:400});
 if(busy.has(worldId))throw Object.assign(new Error('This world is already advancing.'),{statusCode:409});
 if(workers.size>=capacity)throw Object.assign(new Error('All simulation workers are busy. Try again when one finishes.'),{statusCode:409});
 const clock=db.prepare('SELECT seconds FROM lw_worlds WHERE world_id=?').get(worldId);if(!clock)throw new Error('World not found');const id=uid('turbo_'),time=Date.now();
 db.prepare("INSERT INTO living_turbo_jobs(id,world_id,user_id,status,minutes,start_seconds,started_at,updated_at) VALUES (?,?,?,'running',?,?,?,?)").run(id,worldId,user.id,minutes,clock.seconds,time,time);busy.add(worldId);
 let worker;try{worker=new Worker(new URL('./turbo-worker.js',import.meta.url),{workerData:{userId:user.id,worldId,minutes}});}catch(e){busy.delete(worldId);db.prepare("UPDATE living_turbo_jobs SET status='failed',error=? WHERE id=?").run(e.message,id);throw e;}
 workers.set(worldId,worker);let finished=false;
 const finish=(status,error=null,metrics=null)=>{if(finished)return;finished=true;const current=db.prepare('SELECT seconds FROM lw_worlds WHERE world_id=?').get(worldId);db.prepare('UPDATE living_turbo_jobs SET status=?,completed=?,error=?,metrics=?,updated_at=? WHERE id=?').run(status,Math.max(0,Math.floor(((current?.seconds||clock.seconds)-clock.seconds)/60)),error,metrics?JSON.stringify(metrics):null,Date.now(),id);workers.delete(worldId);busy.delete(worldId);};
 worker.on('message',m=>{if(m.type==='progress')db.prepare('UPDATE living_turbo_jobs SET completed=?,updated_at=? WHERE id=?').run(m.completedMinutes,Date.now(),id);else if(m.type==='done')finish('completed',null,m.metrics);else if(['cancelled','failed'].includes(m.type))finish(m.type,m.message);});worker.on('error',e=>finish('failed',e.message));worker.on('exit',code=>{if(!finished)finish('failed','Simulation worker exited ('+code+'). Saved checkpoints remain available.');});return turboStatus(worldId);
}
export function cancelTurbo(worldId){const worker=workers.get(worldId);if(worker){db.prepare("UPDATE living_turbo_jobs SET status='cancelling',updated_at=? WHERE world_id=? AND status='running'").run(Date.now(),worldId);worker.postMessage('cancel');}return turboStatus(worldId);}
export function stopTurboWorkers(){for(const worker of workers.values())worker.postMessage('cancel');}
