#!/usr/bin/env python3
"""Validate sidecars/images, build contact sheets and an offline searchable HTML catalog."""
import collections, datetime, hashlib, html, json, math
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, ImageOps
ROOT=Path(__file__).resolve().parents[1];LIB=ROOT/'assets/living-world-library'
plan=json.loads((LIB/'generation-plan.json').read_text());legacy=json.loads((LIB/'existing-backgrounds.json').read_text());entries=[];problems=[]
for record in legacy['images']:
    entries.append(json.loads((LIB/record['sidecar']).read_text()))
for job in plan['jobs']:
    path=LIB/job['sidecar'];record=json.loads(path.read_text());entries.append(record)
    if record.get('status')!='complete':problems.append({'id':record['id'],'issue':'not_complete','status':record.get('status')});continue
    file=LIB/record['file']
    try:
        with Image.open(file) as image:
            image.verify()
        with Image.open(file) as image:
            assert image.format=='PNG';assert image.size==(record['width'],record['height'])
    except Exception as e:problems.append({'id':record['id'],'issue':'image_validation','detail':str(e)})
    if hashlib.sha256(file.read_bytes()).hexdigest()!=record['sha256']:problems.append({'id':record['id'],'issue':'checksum_mismatch'})
    if Path(record['file']).stem!=Path(record['sidecar']).stem:problems.append({'id':record['id'],'issue':'basename_mismatch'})
    if not record.get('prompt') or not record.get('caption',{}).get('de'):problems.append({'id':record['id'],'issue':'missing_prompt_or_caption'})
    if record.get('model')!='nano-banana-2-lite':problems.append({'id':record['id'],'issue':'wrong_model'})
    if record['kind']=='character' and record.get('technical_review',{}).get('border_green_fraction',0)<.90:problems.append({'id':record['id'],'issue':'green_border_review','value':record.get('technical_review')})
complete=[e for e in entries if (LIB/e['file']).is_file() and (e.get('status')=='complete' or e['origin']=='existing')]
try:font=ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',12);big=ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',18)
except OSError:font=ImageFont.load_default();big=font
for entry in complete:
    with Image.open(LIB/entry['file']) as image:
        image=image.convert('RGB');image.thumbnail((360,300));out=LIB/'previews'/f"{entry['id']}.jpg";image.save(out,quality=85)
    entry['preview']=str(out.relative_to(LIB))

def sheet(name,records,columns,tile_width,tile_height):
    if not records:return
    canvas=Image.new('RGB',(columns*tile_width,60+math.ceil(len(records)/columns)*tile_height),'#eeeaf4');draw=ImageDraw.Draw(canvas);draw.text((16,15),name,fill='#2f2945',font=big)
    for index,e in enumerate(records):
        x=(index%columns)*tile_width;y=60+(index//columns)*tile_height
        with Image.open(LIB/e['file']) as image:
            box=(tile_width-14,tile_height-51);image=ImageOps.contain(image.convert('RGB'),box);canvas.paste(image,(x+(tile_width-image.width)//2,y+5))
        label=e.get('title',e['id'])
        if e['kind']=='character':label=f"{e['gender']} {e['age_months'] if e.get('age_months') else e['age_years']}{'m' if e.get('age_months') else 'y'} · {e['heritage']}"
        draw.text((x+7,y+tile_height-41),label[:39],font=font,fill='#2f2945');draw.text((x+7,y+tile_height-24),e['id'][:37],font=font,fill='#665d78')
    canvas.save(LIB/'review'/f'{name}.jpg',quality=90)
new_backgrounds=[e for e in complete if e['kind']=='background' and e['origin']=='generated']
sheet('new-backgrounds',new_backgrounds,5,280,200)
existing_backgrounds=[e for e in complete if e['origin']=='existing']
for offset in range(0,len(existing_backgrounds),30):sheet('existing-backgrounds-'+str(offset//30+1),existing_backgrounds[offset:offset+30],5,280,200)
for group in plan['age_groups']:
    sheet(group['id'],[e for e in complete if e.get('age_group')==group['id']],5,230,370)
counts={'existing_unique_backgrounds':len(existing_backgrounds),'existing_background_sources':legacy['source_count'],'new_backgrounds_complete':len(new_backgrounds),'characters_complete':sum(e['kind']=='character' for e in complete),'new_images_planned':len(plan['jobs']),'total_unique_images':len(complete)}
manifest={'schema_version':1,'updated_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'counts':counts,'age_groups':plan['age_groups'],'model_for_new_images':plan['model'],'parallel_api_calls':20,'heritage_counts':dict(collections.Counter(e.get('heritage') for e in complete if e['kind']=='character')),'entries':entries}
(LIB/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
report={'checked_at':manifest['updated_at'],'counts':counts,'problems':problems,'review_method':'Technical validation plus manually viewed contact sheets. Design heritage labels are prompt metadata, not inferred classifications.','visual_review':'complete' if all(e.get('review_status')=='visually_reviewed' for e in entries if e['origin']=='generated') else 'pending'}
(LIB/'validation-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
# Embed the catalog so opening this file directly also works (no fetch/file:// CORS).
embedded=json.dumps(manifest,ensure_ascii=False).replace('<','\\u003c')
page='''<!DOCTYPE html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vivarium · Living World Asset Library</title><style>
:root{font-family:system-ui,sans-serif;color:#29253d;background:#f4f1fa;color-scheme:light}*{box-sizing:border-box}body{margin:0}header{padding:45px max(24px,5vw);background:linear-gradient(130deg,#372261,#6d4aff);color:white}header small{letter-spacing:.14em;font-weight:700}h1{font-size:clamp(28px,4vw,46px);margin:12px 0}header p{max-width:780px;line-height:1.6;opacity:.88}.summary{display:flex;gap:12px;flex-wrap:wrap}.summary span{background:#ffffff20;padding:9px 14px;border-radius:10px;font-size:13px}main{padding:26px max(24px,5vw)}.toolbar{display:flex;gap:9px;flex-wrap:wrap;margin-bottom:16px}input,select,button{font:inherit;border:1px solid #d9d1e6;border-radius:8px;padding:10px 12px;background:white;color:inherit}input{min-width:200px;flex:1}button{cursor:pointer}#status{font-size:13px;color:#71687e;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:16px}.card{background:white;border:1px solid #e3dcec;border-radius:14px;overflow:hidden;min-width:0}.card>a{display:flex;align-items:center;justify-content:center;height:190px;background:#eae5f0}.card.character>a{height:275px;background:#d9eadf}.card img{max-width:100%;max-height:100%;object-fit:contain}.details{padding:15px}h2{font-size:15px;margin:0 0 8px}.caption{font-size:12px;line-height:1.6;color:#71687e}.tags{display:flex;flex-wrap:wrap;gap:5px;margin-bottom:9px}.tags span{background:#f2eef8;border-radius:5px;padding:4px 6px;font-size:10px;color:#796b8c}.links{display:flex;gap:15px;font-size:12px;margin-top:12px}a{color:#6b45bd}details{margin-top:12px;font-size:12px}summary{cursor:pointer}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f7f4fb;padding:10px;font:11px/1.6 system-ui,sans-serif;max-height:260px;overflow:auto}.note{margin:22px 0;padding:16px;border-radius:10px;border:1px solid #dcd3eb;font-size:12px;line-height:1.7}.group-info{font-size:11px;color:#7b6d8b}footer{padding:26px;text-align:center;font-size:12px;color:#7a6e86}@media(max-width:550px){header{padding:30px 20px}main{padding:20px}.toolbar>*{width:100%}.grid{grid-template-columns:1fr}}
</style></head><body><header><small>VIVARIUM · LIVING WORLD</small><h1>Die wiederverwendbare Asset-Bibliothek</h1><p>Bestehende Schauplätze und neue Location- sowie Charakter-Assets im vertrauten Anime-Stil. Jedes Bild besitzt eine JSON-Datei mit demselben Basename: Caption, Prompt, Dateipfad und Generierungsdaten.</p><div class="summary" id="counts"></div></header><main><div class="toolbar"><input id="search" type="search" placeholder="Suche nach Location, Outfit, Alter …" aria-label="Assets durchsuchen"><select id="kind" aria-label="Asset-Typ"><option value="all">Alle Assets</option><option value="new-backgrounds">30 neue Hintergründe</option><option value="existing">Bestehende Hintergründe</option><option value="character">90 Charaktere</option></select><select id="age" aria-label="Altersgruppe"><option value="all">Alle Altersgruppen</option></select><select id="gender" aria-label="Geschlecht"><option value="all">Alle Geschlechter</option><option value="male">Männlich</option><option value="female">Weiblich</option></select><select id="heritage" aria-label="Gewünschte Herkunft"><option value="all">Alle Herkunftsdesigns</option><option value="white">Weiß / europäisch</option><option value="black">Schwarz / afroamerikanisch</option><option value="latino">Latino</option><option value="japanese">Japanisch</option><option value="indian">Indisch</option></select></div><div id="status" role="status"></div><div class="grid" id="grid"></div><div class="note">Neue Bilder: <b>nano-banana-2-lite über HyprLab</b>, maximal 20 parallele Generierungsaufrufe. Hintergründe 16:9, Charaktere 2:3. Alle neuen Figuren sind SFW; Minderjährige vollständig und altersgerecht bekleidet. Herkunftsangaben beschreiben das angeforderte fiktive Design. 45 weiße, 12 Schwarze, 11 Latino-, 11 japanische und 11 indische Figuren.<br>Bestandsbilder wurden unverändert kopiert. Byteidentische Duplikate teilen ein Bild; alle Quellen bleiben in den Sidecars erhalten. Historisch nicht gespeicherte Originalprompts sind ausdrücklich als unbekannt markiert. Die Greenscreen-Originale bleiben für späteres Keying erhalten.</div><p><a href="generation-plan.json">Vollständige Prompt- und Asset-Liste</a> · <a href="manifest.json">Asset-Manifest</a> · <a href="validation-report.json">Prüfbericht</a></p></main><footer>Lokale Bibliothek · keine Änderung der Spielstände oder zentralen Modelle</footer><script id="catalog" type="application/json">__DATA__</script><script>
const data=JSON.parse(document.getElementById('catalog').textContent),all=data.entries,$=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));$('counts').innerHTML=`<span>${data.counts.existing_unique_backgrounds} vorhandene Motive · ${data.counts.existing_background_sources} Quellen</span><span>${data.counts.new_backgrounds_complete} neue Locations</span><span>${data.counts.characters_complete} Charaktere</span>`;$('age').innerHTML+=data.age_groups.map(g=>`<option value="${g.id}">${esc(g.label)} · ${g.min_age}–${g.max_age}</option>`).join('');function render(){const query=$('search').value.toLowerCase(),kind=$('kind').value,age=$('age').value,gender=$('gender').value,heritage=$('heritage').value;const list=all.filter(e=>(kind==='all'||kind==='existing'&&e.origin==='existing'||kind==='new-backgrounds'&&e.origin==='generated'&&e.kind==='background'||kind===e.kind)&&(age==='all'||e.age_group===age)&&(gender==='all'||e.gender===gender)&&(heritage==='all'||e.heritage===heritage)&&[e.title,e.caption?.de,e.caption?.en,e.id,e.prompt,...(e.tags||[])].join(' ').toLowerCase().includes(query));$('status').textContent=`${list.length} Assets gefunden`;$('grid').innerHTML=list.map(e=>`<article class="card ${e.kind}"><a href="${esc(e.file)}" target="_blank" rel="noopener">${e.status==='complete'||e.origin==='existing'?`<img loading="lazy" src="${esc(e.preview||e.file)}" alt="${esc(e.caption?.de||e.title)}">`:'Noch nicht generiert'}</a><div class="details"><h2>${esc(e.title)}</h2><div class="tags"><span>${e.origin==='existing'?'Bestand':e.kind==='background'?'Neue Location':'Charakter'}</span><span>${e.aspect_ratio}</span>${e.heritage?`<span>${esc(e.heritage_label)}</span>`:''}${e.sfw?'<span>SFW</span>':''}</div><div class="caption">${esc(e.caption?.de||e.title)}</div><div class="links"><a href="${esc(e.file)}" target="_blank" rel="noopener">Originalbild</a><a href="${esc(e.sidecar)}" target="_blank" rel="noopener">JSON-Sidecar</a></div><details><summary>Caption & verwendeter Prompt</summary><p>${esc(e.caption?.en||'')}</p><pre>${esc(e.prompt||'Der ursprüngliche Prompt wurde damals nicht gespeichert.')}</pre></details></div></article>`).join('');}for(const id of ['search','kind','age','gender','heritage'])$(id).addEventListener(id==='search'?'input':'change',render);render();
</script></body></html>'''
(LIB/'index.html').write_text(page.replace('__DATA__',embedded))
print(json.dumps({'counts':counts,'issues':len(problems),'green_review':[p['id'] for p in problems if p['issue']=='green_border_review']},ensure_ascii=False))
