import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const virtualPython=path.join(root,'.venv','bin','python');
const python=process.env.VIV_PYTHON_BIN || (fs.existsSync(virtualPython)?virtualPython:'python3');
const child=spawn(python,[path.join(root,'scripts/setup-music.py'),...process.argv.slice(2)],{cwd:root,env:process.env,stdio:'inherit'});
child.on('error',error=>{console.error(error.message);process.exitCode=1;});
child.on('close',code=>{process.exitCode=code || 0;});
