import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'vivarium-living-'));process.env.VIV_DATA_DIR=scratch;process.env.VIV_SECRET='test-only-living-world-secret';
const {db}=await import('../server/living/schema.js');
const {createTown,advanceTown,loadTown,allocateFields,busy}=await import('../server/living/engine.js');
const {generateTown}=await import('../server/living/generate.js');
const {openSims,openSimsCatalog,closeOpenSims}=await import('../server/living/open_sims.js');
const {encryptSecret,withPrincipal,isolatedRequest}=await import('../server/byok.js');
const {createSession}=await import('../server/auth.js');
const {buildWorldManifest,importWorldManifest}=await import('../server/world_io.js');
const {recall}=await import('../server/living/memory.js');
const {stageView,graphView,converse,chatHistory,clearChat}=await import('../server/living/vivarium.js');
const {circleMap,searchMap,mapAnchors}=await import('../server/living/map.js');
const {directorChat,directorApply}=await import('../server/living/director.js');
const {default:Fastify}=await import('fastify');const {default:cookie}=await import('@fastify/cookie');
const {default:livingRoutes}=await import('../server/routes/living.js');const {default:apiRoutes}=await import('../server/routes/api.js');
const stamp=new Date().toISOString();
for(const id of ['alice','bob'])db.prepare('INSERT INTO users(id,email,display_name,email_verified_at,created_at,hypr_key,or_enabled) VALUES (?,?,?,?,?,?,1)').run(id,id+'@test.local',id,stamp,stamp,encryptSecret('test-fixture-no-real-provider-key'));
const user=db.prepare('SELECT * FROM users WHERE id=?').get('alice');
const app=Fastify();app.addHook('onRequest',(req,reply,done)=>isolatedRequest(done));await app.register(cookie);await app.register(livingRoutes);await app.register(apiRoutes);
const sessions={alice:'vsession='+createSession('alice'),bob:'vsession='+createSession('bob')};const request=(method,url,payload,who='alice')=>app.inject({method,url,headers:{cookie:sessions[who]},...(payload?{payload}:{})});
const tick=(worldId,options)=>withPrincipal(user,()=>advanceTown(user,worldId,options));
try {
  const catalog=await openSimsCatalog();assert.equal(catalog.manifest.version,'3.3.0');assert.ok(Object.keys(catalog.actions).length>=80);
  const a=await generateTown('one',{population:100,seed:73}),b=await generateTown('two',{population:100,seed:73});assert.deepEqual(a.people.map(p=>[p.name,p.age,p.psychology.big_five]),b.people.map(p=>[p.name,p.age,p.psychology.big_five]));
  for(const p of a.people){assert.ok(p.biography.length>100);assert.ok(p.psychology.ambitions.length);for(const parent of p.family.parent_ids)assert.ok(a.people.find(q=>q.id===parent).age-p.age>=18);if(p.age<18)assert.equal(p.family.partner_id,null);if(p.workplace_id&&p.age>=18)assert.ok(a.places.find(l=>l.id===p.workplace_id).affordances.includes(catalog.jobStations[p.profile.job]?.[0]));}
  const {worldId}=await createTown(user,{population:10});let town=loadTown(worldId);assert.equal(town.people.length,10);assert.equal(db.prepare('SELECT count(*) n FROM lw_journal').get().n,30);
  const sim=town.people[0],visitor=town.people[2],other=town.people[3],room=sim.location_id;
  const fields=allocateFields(town,[],new Map([[27000,new Map([[room,[sim.id,visitor.id]]])]]));assert.ok(fields.some(f=>f.members.includes(sim.id)&&f.members.includes(visitor.id)));
  const phone=allocateFields(town,[{type:'social',id:'call',participants:[sim.id,other.id],facts:{remote:true}}],new Map());assert.ok(phone.some(f=>f.members.includes(other.id)));
  for(const p of town.people)p.anchored=0;town.places.get(sim.household_id).anchored=1;
  assert.ok(allocateFields(town,[],new Map([[1,new Map([[room,[visitor.id]]])]])).some(f=>f.members.includes(visitor.id)));
  town.transitFields=new Map([['edge:fixture',{from:room,to:sim.household_id}]]);assert.ok(allocateFields(town,[],new Map([[2,new Map([['edge:fixture',[visitor.id]]])]])).some(f=>f.members.includes(visitor.id)));
  const snapshot=()=>JSON.stringify(db.prepare('SELECT state,biography,location_id FROM lw_sims WHERE world_id=? ORDER BY id').all(worldId));
  const before=snapshot(),clock=town.world.seconds;await assert.rejects(tick(worldId,{story:true,minutes:5,modelCall:async()=>{throw new Error('fixture provider failure');}}),/fixture provider/);assert.equal(snapshot(),before);assert.equal(loadTown(worldId).world.seconds,clock);assert.equal(busy.has(worldId),false);
  await assert.rejects(tick(worldId,{story:false,expectedVersion:999}),/changed/);assert.equal(snapshot(),before);
  const aborted=new AbortController();aborted.abort();await assert.rejects(tick(worldId,{story:false,signal:aborted.signal}),/cancelled/);assert.equal(snapshot(),before);
  const response=await tick(worldId,{story:true,minutes:5,modelCall:async messages=>{const context=JSON.parse(messages[1].content);assert.ok(context.sims.length<=24);return {content:JSON.stringify({story:'Eine gemeinsame Szene auf Grundlage der tatsächlichen Begegnungen.',thoughts:context.owned.map(id=>({simId:id,eventId:context.events.find(e=>e.participants.includes(id)).id,text:'Ich bin angekommen; vielleicht ergibt sich heute ein gutes Gespräch.',confidence:.6})).concat([{simId:'foreign',eventId:'fake',text:'Must reject'}]),revisions:[{eventId:'fake',category:'flirt'}],intentions:[{simId:context.owned[0],kind:'teleport',destinationId:'foreign'}]})};}});
  assert.ok(response.metrics.modelCalls>0);assert.ok(response.metrics.rejections.length>=3);assert.equal(loadTown(worldId).world.seconds,clock+300);
  for(const p of loadTown(worldId).people)assert.ok(db.prepare('SELECT count(*) n FROM lw_journal WHERE sim_id=?').get(p.id).n>3);
  assert.equal((await request('GET',`/api/living/worlds/${worldId}`,null,'bob')).statusCode,404);assert.equal((await request('GET',`/api/living/worlds/${worldId}/sims/${sim.id}`,null,'bob')).statusCode,404);
  assert.equal((await request('PUT',`/api/living/worlds/${worldId}/anchors`,{kind:'sim',id:other.id,enabled:true})).statusCode,200);assert.equal(loadTown(worldId).byId.get(other.id).biography_mode,'written_pending');
  const hold={};hold.promise=new Promise(resolve=>hold.release=resolve);let entered;const enteredPromise=new Promise(resolve=>entered=resolve);const pending=tick(worldId,{story:true,modelCall:async messages=>{entered();await hold.promise;const context=JSON.parse(messages[1].content);return {content:JSON.stringify({story:'',thoughts:context.owned.map(id=>({simId:id,eventId:context.events.find(e=>e.participants.includes(id)).id,text:'Ich nehme diese Begegnung wahr.',confidence:.6}))})};}});await enteredPromise;
  assert.equal((await request('PUT',`/api/living/worlds/${worldId}/anchors`,{kind:'sim',id:sim.id,enabled:false})).statusCode,409);assert.equal((await request('POST',`/api/living/worlds/${worldId}/grow`,{count:10})).statusCode,409);hold.release();await pending;
  const oldStates=snapshot();const grow=await request('POST',`/api/living/worlds/${worldId}/grow`,{count:10});assert.equal(grow.statusCode,200,grow.body);assert.equal(loadTown(worldId).people.length,20);assert.deepEqual(JSON.parse(snapshot()).filter(p=>JSON.parse(oldStates).some(q=>q.state===p.state)),JSON.parse(oldStates));
  await tick(worldId,{minutes:60,story:false});await tick(worldId,{minutes:60,story:false});assert.ok(loadTown(worldId).people.some(p=>(p.state.career.experience_hours || 0)>0));
  for(const memory of recall(sim.id,'Wohnzimmer Schule'))assert.ok(db.prepare('SELECT 1 FROM lw_journal WHERE sim_id=? AND event_id=?').get(sim.id,memory.id));
  const zipResponse=await request('GET',`/api/worlds/${worldId}/export/zip`);assert.equal(zipResponse.statusCode,200,zipResponse.body.slice(0,300));const zipPath=path.join(scratch,'living.zip'),unpacked=path.join(scratch,'unpacked');fs.writeFileSync(zipPath,zipResponse.rawPayload);fs.mkdirSync(unpacked);execFileSync('unzip',['-q',zipPath,'-d',unpacked]);
  const unsafe=path.join(scratch,'unsafe.zip');execFileSync('python3',['-c',"import zipfile,stat,sys;z=zipfile.ZipFile(sys.argv[1],'w');i=zipfile.ZipInfo('assets/link');i.create_system=3;i.external_attr=(stat.S_IFLNK|0o777)<<16;z.writestr(i,'/etc/hostname');z.close()",unsafe]);assert.throws(()=>execFileSync('python3',['scripts/unpack-world.py',unsafe,path.join(scratch,'unsafe-unpacked')],{stdio:'pipe'}));
  const childCode="import fs from 'node:fs';import assert from 'node:assert/strict';import {db} from './server/living/schema.js';import {importWorldManifest} from './server/world_io.js';import {loadTown} from './server/living/engine.js';import {assetFile} from './server/living/library.js';db.prepare(\"INSERT INTO users(id,email,display_name,created_at) VALUES ('restore','restore@local','Restore',datetime('now'))\").run();const manifest=JSON.parse(fs.readFileSync(process.argv[1]+'/manifest.json'));const restored=importWorldManifest({id:'restore'},manifest,process.argv[1]+'/assets');const town=loadTown(restored.worldId);assert.equal(town.people.length,20);for(const p of town.people)if(p.asset_id)assert.ok(assetFile(p.asset_id,'full'));db.close();";
  execFileSync(process.execPath,['--input-type=module','-e',childCode,unpacked],{cwd:path.resolve('.'),env:{...process.env,VIV_DATA_DIR:path.join(scratch,'fresh-install'),VIV_LIVING_LIBRARY:path.join(scratch,'absent-library')},stdio:'pipe'});
  const exportManifest=buildWorldManifest(worldId);assert.equal(exportManifest.living.lw_sims.length,20);exportManifest.world.title+=' · copy';const copy=importWorldManifest(user,exportManifest,null);const restored=loadTown(copy.worldId);assert.equal(restored.people.length,20);assert.equal(restored.world.seconds,loadTown(worldId).world.seconds);assert.ok(restored.people.every(p=>p.id!==sim.id));for(const p of restored.people)for(const id of Object.keys(p.relations))assert.ok(restored.byId.has(id));
  assert.ok(db.prepare('SELECT count(*) n FROM lw_journal WHERE sim_id=?').get(restored.people[0].id).n>3);await tick(copy.worldId,{story:false});const copyGrowth=await request('POST',`/api/living/worlds/${copy.worldId}/grow`,{count:10});assert.equal(copyGrowth.statusCode,200);assert.equal([...loadTown(copy.worldId).places.values()].filter(p=>p.kind==='city').length,1);
  const deleted=await request('DELETE',`/api/worlds/${copy.worldId}`);assert.equal(deleted.statusCode,200);assert.equal(db.prepare('SELECT count(*) n FROM lw_sims WHERE world_id=?').get(copy.worldId).n,0);assert.equal(db.prepare('SELECT count(*) n FROM lw_events WHERE world_id=?').get(copy.worldId).n,0);
  const dutyTown=await createTown(user,{population:10}),dutyState=loadTown(dutyTown.worldId),pupil=dutyState.people.find(p=>p.age>=6&&p.age<18);pupil.state.action=null;pupil.state.needs=Object.fromEntries(Object.keys(pupil.state.needs).map(k=>[k,0]));pupil.state.goal={kind:'read',destination:pupil.profile.home.living,expires:36000,source:'storyteller'};db.prepare('UPDATE lw_sims SET state=? WHERE id=?').run(JSON.stringify(pupil.state),pupil.id);db.prepare('UPDATE lw_worlds SET seconds=28800 WHERE world_id=?').run(dutyTown.worldId);await tick(dutyTown.worldId,{minutes:5,story:false});const schoolDay=loadTown(dutyTown.worldId).byId.get(pupil.id);assert.equal(schoolDay.state.goal,null);assert.ok(schoolDay.state.location_id===pupil.profile.workplace_id||schoolDay.state.route?.destination===pupil.profile.workplace_id);
  schoolDay.state.location_id=pupil.profile.workplace_id;schoolDay.state.action=null;schoolDay.state.route=null;schoolDay.state.needs=Object.fromEntries(Object.keys(schoolDay.state.needs).map(k=>[k,k==='bladder'?.9:0]));db.prepare('UPDATE lw_sims SET state=? WHERE id=?').run(JSON.stringify(schoolDay.state),pupil.id);db.prepare('UPDATE lw_worlds SET seconds=39600 WHERE world_id=?').run(dutyTown.worldId);await tick(dutyTown.worldId,{minutes:1,story:false});const bathroomRoute=loadTown(dutyTown.worldId).byId.get(pupil.id).state.route;assert.equal(bathroomRoute.transport,'supervised_school_activity');assert.equal(bathroomRoute.destination,pupil.profile.facility.rooms.wc);
  const minor=a.people.find(p=>p.age<18);assert.equal((await openSims('social',{now:0,pairs:[{a:a.people[0],b:minor,category:'flirt',seed:1,eventId:'test'}]}))[0].allowed,false);
  // Original stage presentation, hierarchical LOD, paused conversations and reviewed GM changes.
  const integration=await createTown(user,{population:500,seed:73}),iw=integration.worldId,initial=loadTown(iw),person=initial.people[0],worldRow=db.prepare('SELECT * FROM worlds WHERE id=?').get(iw);
  const neighborhood=initial.places.get(person.household_id).parent_id;
  const cityGraph=graphView(iw),streetGraph=graphView(iw,{focus:neighborhood,depth:1}),houseGraph=graphView(iw,{focus:person.household_id,depth:2});
  assert.ok(cityGraph.nodes.every(p=>p.kind!=='room'));assert.ok(streetGraph.nodes.some(p=>p.kind==='building'&&!p.landmark));assert.ok(houseGraph.nodes.some(p=>p.kind==='room'));assert.ok(houseGraph.nodes.filter(p=>p.kind==='neighborhood'&&p.id!==neighborhood).every(p=>p.coarse&&!p.thumbnail));
  for(const graph of [cityGraph,streetGraph,houseGraph]){assert.ok(graph.nodes.length<=60);assert.ok(graph.nodes.filter(n=>n.thumbnail).length<=60);for(const e of graph.edges){assert.ok(graph.nodes.some(n=>n.id===e.from_id));assert.ok(graph.nodes.some(n=>n.id===e.to_id));}}
  assert.throws(()=>graphView(iw,{focus:'foreign'}));
  const clockBeforeMap=JSON.stringify(initial.world),neighborhoodIds=[...initial.places.values()].filter(p=>p.kind==='neighborhood').map(p=>p.id);
  const circles=circleMap(iw,{expanded:JSON.stringify([neighborhoodIds[0],neighborhoodIds[1],person.household_id])});
  assert.ok(circles.expanded.includes(neighborhoodIds[0])&&circles.expanded.includes(neighborhoodIds[1]));
  assert.ok(circles.nodes.some(n=>n.parent_id===person.household_id&&n.kind==='room'));
  const street='map:street:'+neighborhoodIds[0];assert.ok(circles.nodes.some(n=>n.id===street&&n.virtual&&n.placeId===neighborhoodIds[0]));
  assert.ok(circles.edges.some(e=>e.from_id===street||e.to_id===street));
  assert.ok(circles.edges.some(e=>[e.from_id,e.to_id].includes(street)&&[e.from_id,e.to_id].includes('map:street:'+neighborhoodIds[1])));
  assert.ok(circles.nodes.length<=180&&circles.nodes.filter(n=>n.thumbnail).length<=50);
  for(const roomNode of circles.nodes.filter(n=>n.kind==='room'))assert.ok(circles.edges.some(e=>e.from_id===roomNode.id||e.to_id===roomNode.id),'Every visible room has a doorway path');
  const partyRows=db.prepare('SELECT id,state,location_id FROM lw_sims WHERE world_id=? ORDER BY id LIMIT 8').all(iw),partyPlace=circles.nodes.find(n=>n.kind==='room').id;
  for(const s of partyRows){const state=JSON.parse(s.state);state.location_id=partyPlace;state.route=null;db.prepare('UPDATE lw_sims SET location_id=?,state=? WHERE id=?').run(partyPlace,JSON.stringify(state),s.id);}
  const partyMap=circleMap(iw,{expanded:JSON.stringify([person.household_id])}),partyNode=partyMap.nodes.find(n=>n.id===partyPlace);assert.ok(partyNode.presentCount>=8);assert.equal(partyNode.presentSims.length,4);assert.equal(partyNode.overflow,partyNode.presentCount-4);
  for(const s of partyRows)db.prepare('UPDATE lw_sims SET location_id=?,state=? WHERE id=?').run(s.location_id,s.state,s.id);
  const selectedNames=new URLSearchParams({firstName:person.name.split(' ')[0],familyName:person.name.split(' ').slice(1).join(' '),neighborhood,minAge:String(person.age),maxAge:String(person.age)});
  const filtered=(await request('GET',`/api/living/worlds/${iw}/sims?${selectedNames}`)).json();assert.ok(filtered.sims.some(p=>p.id===person.id));assert.ok(filtered.sims.every(p=>p.age===person.age));
  const unanchored=(await request('GET',`/api/living/worlds/${iw}/sims?anchored=0&limit=50`)).json();assert.ok(unanchored.total>=498);assert.ok(unanchored.sims.every(p=>!p.anchored));
  assert.equal((await request('GET',`/api/living/worlds/${iw}/sims?minAge=bad`)).statusCode,400);assert.equal((await request('GET',`/api/living/worlds/${iw}/sims?neighborhood=foreign`)).statusCode,404);
  assert.equal((await request('GET',`/api/living/worlds/${iw}/sims/filters`,null,'bob')).statusCode,404);
  assert.throws(()=>circleMap(iw,{expanded:'["foreign"]'}));
  assert.equal(searchMap(iw,'Library').results[0].id,searchMap(iw,'Bibliothek').results[0].id);
  assert.ok(searchMap(iw,'Library').results[0].path.some(p=>p.kind==='city'));
  const navAnchors=mapAnchors(iw).anchors;assert.ok(navAnchors.some(a=>a.id===person.id&&a.target.type==='character'&&a.revealId===person.location_id));
  assert.equal(JSON.stringify(loadTown(iw).world),clockBeforeMap);
  assert.equal((await request('GET',`/api/living/worlds/${iw}/map`,null,'bob')).statusCode,404);
  assert.equal((await request('GET',`/api/living/worlds/${iw}/map/search?q=library`,null,'bob')).statusCode,404);
  assert.equal((await request('GET',`/api/living/worlds/${iw}/map/anchors`,null,'bob')).statusCode,404);
  const originalPerson=db.prepare('SELECT state,location_id FROM lw_sims WHERE id=?').get(person.id),travelState=JSON.parse(originalPerson.state);
  const routeNode=initial.places.get(person.household_id).parent_id;
  travelState.location_id=null;travelState.route={from:originalPerson.location_id,destination:originalPerson.location_id,index:1,path:[{id:routeNode,seconds:120},{id:originalPerson.location_id,seconds:120}],remaining:60};
  db.prepare('UPDATE lw_sims SET state=?,location_id=NULL WHERE id=?').run(JSON.stringify(travelState),person.id);
  const travellingScene=await stageView(worldRow,{sim:person.id});assert.equal(travellingScene.locations[0].id,routeNode);assert.equal(travellingScene.journey.simId,person.id);assert.equal(travellingScene.characters.length,1);assert.equal(travellingScene.characters[0].state.location_id,null);
  const travellingAnchor=mapAnchors(iw).anchors.find(a=>a.id===person.id);assert.equal(travellingAnchor.revealId,routeNode);assert.equal(travellingAnchor.travelling,true);
  db.prepare('UPDATE lw_sims SET state=?,location_id=? WHERE id=?').run(originalPerson.state,originalPerson.location_id,person.id);
  // Budget holds even with many independent neighborhoods added through growth.
  const extraPlaces=[];for(let k=0;k<90;k++){const district='test_d_'+k,neighbor='test_n_'+k;extraPlaces.push(district,neighbor);db.prepare('INSERT INTO lw_places(id,world_id,parent_id,name,kind,purpose) VALUES (?,?,?,?,?,?)').run(district,iw,cityGraph.ancestors.find(p=>p.kind==='city').id,'Extra district '+k,'district','district');db.prepare('INSERT INTO lw_places(id,world_id,parent_id,name,kind,purpose) VALUES (?,?,?,?,?,?)').run(neighbor,iw,district,'Extra neighborhood '+k,'neighborhood','street');}
  const manyRoots=circleMap(iw,{focus:'test_n_89',expanded:JSON.stringify(['test_d_89'])});assert.ok(manyRoots.nodes.length<=180);assert.ok(manyRoots.omittedRoots>0);assert.ok(manyRoots.nodes.some(n=>n.id==='test_n_89'));
  for(const id of extraPlaces.reverse())db.prepare('DELETE FROM lw_places WHERE id=?').run(id);
  const view=await stageView(worldRow,{sim:person.id});assert.equal(view.world.simulation_mode,'living');assert.ok(view.characters.length<=17);assert.ok(view.locations[0].background_asset_id.startsWith('/api/living/library/'));assert.ok(view.characters[0].state.outfits[0].cutout_asset_id.includes('variant=sprite'));
  assert.equal((await request('GET',`/api/worlds/${iw}?sim=${person.id}`,null,'bob')).statusCode,404);
  assert.equal((await request('GET',`/api/living/worlds/${iw}/graph`,null,'bob')).statusCode,404);
  assert.equal((await request('POST',`/api/living/worlds/${iw}/sims/${person.id}/talk`,{message:'Hallo'},'bob')).statusCode,404);
  const beforeTalk=loadTown(iw).world.seconds,oldThought=person.state.thought;
  const chat=await withPrincipal(user,()=>converse(user,iw,person.id,{message:'Wie geht es dir?',channel:'inner',modelCall:async messages=>{const ctx=JSON.parse(messages[1].content);assert.equal(ctx.name,person.name);assert.ok(ctx.memory.every(m=>db.prepare('SELECT 1 FROM lw_journal WHERE sim_id=? AND event_id=?').get(person.id,m.id)));return {content:JSON.stringify({reply:'Ich freue mich auf einen ruhigen Tag.',thought:'Eine freundliche Frage tut mir gut.',mood:'hopeful'})};}}));
  assert.equal(chat.reply,'Ich freue mich auf einen ruhigen Tag.');assert.equal(loadTown(iw).world.seconds,beforeTalk);assert.equal(chatHistory(iw,person.id).length,2);assert.equal(chatHistory(iw,initial.people[5].id).length,0);assert.ok(recall(person.id,'freundliche Frage').length>0);
  clearChat(iw,person.id);assert.equal(chatHistory(iw,person.id).length,0);assert.equal(loadTown(iw).byId.get(person.id).state.thought,oldThought);
  const v=loadTown(iw).world.version;await assert.rejects(converse(user,iw,person.id,{message:'Hallo',modelCall:async()=>({content:'broken-json'})}));assert.equal(loadTown(iw).world.version,v);assert.equal(busy.has(iw),false);
  const target=initial.people.find(p=>!p.anchored),intervention={kind:'idea',targetId:target.id,text:'Vielleicht könntest du deiner Nachbarin später helfen.'};let gotIntervention=false;
  await tick(iw,{minutes:1,intervention,modelCall:async messages=>{const ctx=JSON.parse(messages[1].content);if(ctx.owned.includes(target.id)){gotIntervention=true;assert.equal(ctx.intervention.targetId,target.id);}
    const e=ctx.events.find(e=>e.participants.includes(ctx.owned[0])&&e.location_id);return {content:JSON.stringify({story:'Ein kurzer Augenblick.',thoughts:ctx.owned.map(id=>({simId:id,eventId:ctx.events.find(e=>e.participants.includes(id)).id,text:'Ich überlege, wie ich heute jemandem helfen kann.'})),narration:[{speaker:ctx.owned[0],locationId:e.location_id,eventId:e.id,text:'Guten Morgen!',mode:'speech'},{speaker:'foreign',locationId:e.location_id,eventId:e.id,text:'Must reject',mode:'speech'}]})};}});
  assert.ok(gotIntervention);assert.ok(db.prepare('SELECT 1 FROM lw_journal j JOIN lw_events e ON e.id=j.event_id WHERE j.sim_id=? AND e.type=?').get(target.id,'intervention'));assert.equal(loadTown(iw).byId.get(target.id).anchored,0);assert.ok(db.prepare('SELECT count(*) n FROM lw_scene_lines WHERE world_id=?').get(iw).n>0);
  const dm=await directorChat(user,worldRow,'Setze einen Anker.', 'de',async()=>({content:JSON.stringify({reply:'Ich schlage diesen Anker vor.',actions:[{type:'set_anchor',kind:'sim',id:person.id,enabled:false},{type:'set_anchor',kind:'sim',id:'foreign',enabled:true}]})}));assert.equal(dm.actions.length,1);assert.equal(loadTown(iw).byId.get(person.id).anchored,1);
  await directorApply(user,worldRow,dm.actions);assert.equal(loadTown(iw).byId.get(person.id).anchored,0);assert.equal(loadTown(iw).world.seconds,beforeTalk+60);await assert.rejects(directorApply(user,worldRow,[{type:'set_anchor',kind:'sim',id:'foreign',enabled:true}]));
  const replay=buildWorldManifest(iw),copy2=importWorldManifest(user,replay,null);assert.equal(db.prepare('SELECT count(*) n FROM lw_scene_lines WHERE world_id=?').get(copy2.worldId).n,replay.living.lw_scene_lines.length);assert.ok((await stageView(db.prepare('SELECT * FROM worlds WHERE id=?').get(copy2.worldId))).lastTick.narration.length);
  console.log('PASS original stage adapter, bounded circular multi-group map, bilingual search, travelling anchor view and actual projected paths, private paused conversations and personal memory, conversation clearing and rollback, targeted interventions, validated scene dialogue, GM proposed anchors and ZIP restoration');
  console.log('PASS actual Open Sims registry, seeded biographies/families, workplaces, anchor fields/contact closure, personal memories, atomic failure/cancellation, bounded model contexts, invalid proposal rejection, ownership, mutation locks, growth and complete snapshot copying');
}finally{await app.close();closeOpenSims();db.close();fs.rmSync(scratch,{recursive:true,force:true});}
