"""Document the PERMA-inspired v1 actually present in Living World."""

def section():
    return '''
<section id="wellbeing">
<span class="eyebrow">Individuelles Wohlbefinden · implementierte erste Version</span>
<h2>PERMA: fünf Bereiche statt eines beliebigen Glücksbalkens</h2>
<p>Seligmans Wohlbefindensmodell unterscheidet <strong>positive Gefühle, Engagement, Beziehungen, Sinn und Gelingen</strong>. Das erklärt, warum ein Sim zugleich besorgt sein und eine sinnvolle Aufgabe verfolgen kann: momentane Freude und ein erfülltes Leben sind verschiedene Dinge. Die fünf Bereiche bleiben einzeln sichtbar; ein gleichgewichteter Mittelwert ist lediglich eine Orientierung, keine abschließende Definition von Glück. <a href="https://www.authentichappiness.sas.upenn.edu/learn/wellbeing">Seligmans Darstellung beim Penn Authentic Happiness Center</a>, <a href="https://ppc.sas.upenn.edu/node/708">Penn Positive Psychology Center: PERMA</a>.</p>
<div class="callout"><strong>Was bereits läuft:</strong> Jeder Living-World-Sim hat fünf aus seinem Zustand und seinen eigenen Erfahrungen abgeleitete Werte, angezeigt von 0 bis 100. Abgeschlossene Tätigkeiten, tatsächlicher eigener Zielprogress, angenommene oder abgelehnte Begegnungen und begrenzte subjektive Reaktionen verändern sie. Profil und Mind zeigen die Werte und jüngste eigene Erfahrungsquellen. Das große Wirtschafts- und ToM-System unten ist weiterhin ein Vorschlag; dieser PERMA-Kern ist separat umgesetzt.</div>
<p><strong>Messung im Spiel:</strong> Dies ist eine offen dokumentierte, noch nicht empirisch kalibrierte Spielheuristik, inspiriert von PERMA. Sie ist weder der validierte PERMA-Profiler-Fragebogen noch eine psychologische Diagnose oder eine klinische Behauptung. Es gibt keine Pflicht, in allen fünf Bereichen maximal zu sein. Der tatsächliche PERMA-Profiler ist ein eigenständiges Messinstrument: <a href="https://internationaljournalofwellbeing.org/index.php/ijow/article/view/526">Butler &amp; Kern (2016)</a>. Seine Validierung wird nicht auf diese Spielzahlen übertragen.</p>
<div class="tablewrap"><table><thead><tr><th>Bereich</th><th>Was im Spiel gemeint ist</th><th>Bereits wirksame eigene Quellen</th><th>Was daraus nicht folgt</th></tr></thead><tbody>
<tr><td><strong>P · Positive Gefühle</strong></td><td>Angenehmes eigenes Gefühlserleben, mit einer kurzfristigen Komponente für den jetzigen Zustand.</td><td>Tatsächlich ausgeübtes passendes Interesse, freiwilliger Kontakt, selbst erlebter Streit oder eine Ablehnung; validierte eigene emotionale Deutung. Aktuelle Freude oder Belastung und dringende körperliche Bedürfnisse beeinflussen nur diese kurzfristige Komponente.</td><td>Ein freundlicher Satz löscht Hunger, Schulden, Trauer oder einen Konflikt nicht. Freude überschreibt nicht alle anderen Bereiche.</td></tr>
<tr><td><strong>E · Engagement</strong></td><td>Erlebte aktive Beschäftigung; eine zu den eigenen Interessen passende Tätigkeit wird stärker gewichtet.</td><td>Abgeschlossene aktive Tätigkeiten, nach tatsächlicher Dauer begrenzt; gemeinsames Spielen, geteiltes Interesse und Zusammenarbeit. Schlafen, Warten und reine körperliche Versorgung erhalten keinen pauschalen Engagementbonus.</td><td>Ein beendeter Arbeitsschritt ist keine Garantie für Flow oder Freude am Beruf. V1 misst Beteiligung, noch keine psychologisch vollständige Qualität von Flow.</td></tr>
<tr><td><strong>R · Beziehungen</strong></td><td>Erlebte verlässliche und freiwillige soziale Verbindung, romantisch oder nicht.</td><td>Angenommener Kontakt, Hilfe, Zuspruch und Versöhnung; tatsächlich erlebter Streit belastet den Wert. Eine Ablehnung kann enttäuschen, senkt aber nicht automatisch R.</td><td>Mehr Kontakte sind nicht immer bessere Beziehungen. Grenzen setzen oder einen Kontakt ablehnen ist keine schlechte Beziehung und wird nicht als moralisches Fehlverhalten bestraft. Partnerschaft oder Sexualität sind keine Voraussetzung für einen hohen R-Wert.</td></tr>
<tr><td><strong>M · Sinn &amp; Zugehörigkeit</strong></td><td>Eigenen Vorhaben näherkommen und tatsächlich füreinander da sein.</td><td>Tatsächlicher Fortschritt einer eigenen Ambition; erlebte Hilfe, Fürsorge, ein persönlicher Check-in und ein Schritt zur Versöhnung.</td><td>Eine fremd zugewiesene Aufgabe, ein großer Kontostand oder ein schöner Satz erzeugt keinen automatisch tiefen Lebenssinn. Die genauere Passung zu Werten und selbst gewählten Verpflichtungen ist ein späterer Ausbau.</td></tr>
<tr><td><strong>A · Erlebtes Gelingen</strong></td><td>Einen wirklichen eigenen Lern-, Übungs- oder Zielschritt schaffen, auch ohne äußeren Status.</td><td>Gültiger, bereits im Simulationskern gemessener Ambitionsprogress; begrenzte eigene Lernpraxis bei Schule, Kindergarten, Lesen und kreativem Hobby.</td><td>Ein bloßer Wunsch, ein geplanter Erfolg, ein behauptetes Diplom oder vom Modell gelieferte Glückszahlen werden nicht zu tatsächlichem Gelingen. Praxis ist ein kleiner Erfolg, keine erfundene Meisterschaft.</td></tr>
</tbody></table></div>
<h3>Persönliche Ausgangslage ohne erfundene Glücksbiografie</h3>
<p>Neue und migrierte Sims starten mit einer neutralen Basis von 0,5 je Bereich. R erhält eine kleine Korrektur aus den bereits gespeicherten <em>eigenen</em> Vertrauenseinschätzungen von höchstens 24 Beziehungen. Die Gegenwartsanteile von P kommen aus den tatsächlichen Gefühlen und körperlichen Bedürfnissen. Bereits initialisierte Ambitionsstände, Wohlstand oder eine geschriebene Biografie werden nicht nachträglich als neue glückliche Erlebnisse gebucht. Das verhindert doppelte Hintergrundboni. Ein neutraler Wert bedeutet „noch nicht durch viele neue Erfahrungen gestützt“, nicht „dieser Mensch ist psychologisch exakt halb glücklich“.</p>
<p>Auch Kinder und Senioren erhalten die fünf Spielbereiche, mit ihren bestehenden altersgerechten Aktivitäten und Zielen. Bei Kleinkindern sind sie eine vorsichtige modellierte Perspektive auf Versorgung, Nähe und Entdeckung, kein vermeintlicher Selbstauskunftstest. Die Interpretation bleibt altersgerecht; es gibt weder romantische Pflicht noch Sexualität als Glückserfordernis. Alle vorhandenen Alters- und Zustimmungsregeln gelten unverändert.</p>
<h3>Nachvollziehbare Veränderung, Erinnerung und Zeitskala</h3>
<p>Jeder direkte Erfahrungsbeitrag enthält eine echte Ereignis-ID, Simulationszeit, Kanal, eine begrenzte Änderung pro Bereich und eine erklärende Begründung. Er gehört ausschließlich diesem Sim. Tätigkeit und Begegnung werden zusammen mit ihren persönlichen Protokollen atomar gespeichert. Eine nur geplante oder abgebrochene Handlung erzeugt keinen Erfahrungsbeitrag. Gespräch und Storyteller bekommen die eigenen PERMA-Werte und jüngsten eigenen Quellen als abgeleiteten Kontext; sie können keine Punktzahlen setzen.</p>
<div class="tablewrap"><table><thead><tr><th>Spielparameter in V1</th><th>Regel</th><th>Zweck und Grenze</th></tr></thead><tbody>
<tr><td>Skala und Mittelwert</td><td>Interne Werte 0–1, Anzeige 0–100; alle fünf Bereiche gleichgewichtet im optionalen Mittelwert.</td><td>Die Einzelwerte bleiben maßgeblich. Keine Rangliste menschlichen Werts und keine Belohnung für Reichtum.</td></tr>
<tr><td>Einzelbeitrag</td><td>Höchstens ±0,04 je Bereich und Ereigniskanal; ein bereits vorhandenes Ereignis/Kanal-Paar wird nicht nochmals gebucht.</td><td>Keine plötzlichen riesigen Glückssprünge durch einen Satz; Wiederholungen bleiben begrenzt.</td></tr>
<tr><td>Tagesgrenze</td><td>Je Bereich und Simulationstag höchstens +0,08 positive und −0,10 negative Erfahrungsbeiträge; die Grenzen werden vor dem Zeitzerfall berechnet.</td><td>Viele kurze Aktionen dürfen nicht beliebig Punkte sammeln. Neu zeichnen, Browsernavigation oder kleine statt großer Anzeigeintervalle ändern dieselben Quellen nicht.</td></tr>
<tr><td>Unterschiedliche Erinnerung</td><td>Illustrative Halbwertszeiten: P 2 Tage, E 5 Tage, R 14 Tage, M 21 Tage, A 10 Tage. Nur fortschreitende Simulationszeit zählt.</td><td>Gefühlsmomente klingen schneller ab als erlebte Verbundenheit und Sinn. Das sind frei gewählte Spielparameter, keine wissenschaftlich ermittelten PERMA-Konstanten.</td></tr>
<tr><td>Begrenzter Hot-State</td><td>Höchstens 128 jüngste beitragende Quellen je Sim. Ältere Quellen bleiben im vollständigen persönlichen Ereignisprotokoll erhalten, fließen in V1 aber nicht mehr direkt in diese Projektion ein.</td><td>Die erste Version ist ein begrenztes Erfahrungsfenster, keine vollständige Lebensbilanz. Bei sehr aktiven Sims kann das Fenster kürzer werden. Vor langfristiger Kalibrierung sind zeitbasierte Tagesaggregate mit reversiblen Quellen statt einer reinen Anzahlgrenze einzuführen.</td></tr>
<tr><td>Eigene Deutung</td><td>Validierte emotionale Modellreaktionen können P begrenzt beeinflussen; R/M/E/A entstehen daraus nicht automatisch.</td><td>Falsche Erwartungen bleiben subjektiv. Das Modell kann weder einen tatsächlichen Erfolg noch eine Beziehung durch eine Behauptung herstellen.</td></tr>
<tr><td>Gespräch löschen</td><td>Nur die Quellen dieses gelöschten Gesprächskanals werden entfernt; spätere echte Tätigkeiten und ihre Quellen bleiben bestehen.</td><td>Keine verwaisten Glücksboni, keine pauschale Löschung späterer Erfahrungen; die Weltzeit bleibt stehen.</td></tr>
</tbody></table></div>
<h3>Organisch mit Bedürfnissen, Persönlichkeit, ToM und Wirtschaft verbinden</h3>
<p>Die bestehenden Bedürfnisse bleiben Dringlichkeiten: hoch heißt unbefriedigt. PERMA bedeutet dagegen besser gestütztes Wohlbefinden: hoch heißt günstiger. Die UI erklärt beide Richtungen ausdrücklich. Hunger bleibt Hunger; dessen Versorgung kann ein angenehmer Moment sein, ist aber kein sofort erfülltes Lebensziel. Interessen beeinflussen Engagement, Ambitionen liefern persönliche Zielschritte, und die bereits individuell ausgelösten Gefühle verändern den Gegenwartsanteil von P. So bleiben Wohlbefinden, Bedürfnisse, Gedanken und Ziele verschiedene, zusammenhängende Größen.</p>
<p><strong>Mit dem geplanten Wirtschaftssystem:</strong> Kontostand, Einkommensklasse und Konsumpreis werden niemals direkt in Glück umgerechnet. Eine hohe Miete kann über die tatsächliche eigene Prognose Sorgen auslösen; eine bezahlte Rechnung kann Sicherheit geben, tatsächliche hilfreiche Unterstützung R/M stärken. Ein kostenloser Spaziergang oder ein gemeinsam geschaffenes Werk kann E/A erhöhen. Ein Luxusgegenstand liefert erst dann eine Quelle, wenn er tatsächlich passend benutzt oder persönlich bedeutsam erlebt wird. Dieselbe Rechnung darf nicht nochmals als Bedürfnisstrafe, Emotion und pauschaler Glücksabzug dreifach wirken.</p>
<p><strong>Mit dem geplanten ToM-System:</strong> Erwartungen an andere beeinflussen die Deutung eines wirklichen Ereignisses, nicht dessen Fakten. Eine unerwartete freundliche Hilfe kann vorsichtige Hoffnung und Vertrauen stützen; ein nachweislich gebrochenes Versprechen kann Beziehungen belasten. Die späteren Kategorien brauchen deshalb eigene appraisal-Felder für freiwillige Verbundenheit, Passung zu persönlichen Werten, Schwierigkeit/Kompetenz und erwartete gegenüber tatsächlicher Unterstützung. Fremde Gedanken bleiben unbekannt. Ein niedriger Wert ist weder Zustimmung zu einer Annäherung noch ein pauschaler Auslöser von Kriminalität oder psychischer Krankheit.</p>
<p><strong>Mit dem W100-System:</strong> Der vorhandene echte Handlungs- und Zielstand ist die Quelle, nicht der Erfolgswunsch des Storytellers. Im erweiterten Plan werden gelungener Versuch, nachvollziehbar hilfreiche Übung, gemischtes Resultat und Rückschlag getrennt bewertet. Zufallswurf, Schwierigkeit und eigene Bewertung müssen im Ereignis stehen; ein misslungener Versuch darf trotzdem etwas lehren, aber keinen abgeschlossenen Erfolg buchen. Wertepassung und Qualität einer Tätigkeit sollen später den heutigen groben Engagementbeitrag verfeinern.</p>
<h3>Implementationspunkte, Migration und Nachweis</h3>
<pre>state.wellbeing = {
  version: 1, initialized_at, updated_at, origin,
  baseline: {P, E, R, M, A}, scores: {P, E, R, M, A}, summary,
  evidence: [{eventId, at, channel, delta: {P,E,R,M,A}, reason}]
}
activity_completed / final_validated_social / witnessed_reflection
  → own evidence → bounded daily projection → personal profile &amp; Mind
budget/job/housing events (future)
  → actual own consequence &amp; appraisal → same pathway, no money bonus</pre>
<p><code>server/living/wellbeing.js</code> enthält die Projektion und ihre Regeln; <code>cognition.js</code> bindet abgeschlossene Tätigkeiten, endgültig validierte Begegnungen und eigene Reflexionen ein. Die Regeln werden nicht auf einer noch provisorischen sozialen Modellrevision gebucht. <code>upgrade-wellbeing.js</code> sichert die Datenbank vor der einmaligen Ergänzung bestehender Welten; Uhrzeit, Orte, Biografien, körperliche Bedürfnisse und alte Ereignisse bleiben erhalten. Die Weltversion steigt für neue Requests. ZIP-Export und Duplikation übernehmen Zustand und remappen die Ereignis-IDs. Profil und Mind nutzen dieselbe Projektion, keine unabhängig berechneten Glücksanzeigen.</p>
<p><code>npm run test:living-wellbeing</code> prüft unter anderem echte Zielschritte, getrennte Bereiche, Hilfe/Konflikt/Ablehnung, ausbleibende Geld- und Fantasieerfolgsboni, körperlichen Druck, Tagesgrenzen und Zerfall, idempotente Anzeige, journalgestützte echte Engine-Ereignisse, pausierte Gespräche samt selektiver Rücknahme, Quellen-Remapping und abgesicherte einmalige Migration. Die bestehenden Simulations-, Bedürfnis-, Altersgrenzen- und Browserprüfungen ergänzen das. Diese Funktionsnachweise sind keine empirische Validierung menschlichen Glücks.</p>
</section>
'''
