'use strict';
function turboDuration(ms){const seconds=Math.max(0,Math.round(ms/1000));return seconds<60?seconds+' s':seconds<3600?Math.floor(seconds/60)+' min '+seconds%60+' s':(seconds/3600).toFixed(1)+' h';}
async function livingTurboModal(){
 const world=S.world,url=`/api/living/worlds/${world}/turbo`,m=lwModal('Turbo · let the town live','Every resident advances in one-minute ticks, including anchored Sims.',`<p>Turbo temporarily runs everyone on procedural rules. It makes no Storyteller calls and preserves your anchors for normal Play afterward. Birthdays, work, relationships, money, travel and personal event journals keep running.</p><label>Time to advance<select id="lw-turbo-duration"><option value="60">1 hour</option><option value="360">6 hours</option><option value="1440" selected>1 day</option><option value="4320">3 days</option><option value="10080">1 week</option><option value="43200">30 days</option><option value="525600">365 days</option></select></label><p>A longer period still computes every minute. Large towns and a full year can take substantial real time and disk space; an estimate appears after the first saved hour.</p><button class="btn btn-teal" id="lw-turbo-start">Start Turbo</button><section id="lw-turbo-status" aria-live="polite"></section><p class="ex-muted">You may close this window and return later. Stop keeps completed hourly checkpoints and discards the unfinished hour. Keep the server running; a server restart stops the job at its last saved checkpoint.</p>`,760);
 let timer;const display=job=>{const active=job&&['running','cancelling'].includes(job.status);$('#lw-turbo-start',m).disabled=!!active;$('#lw-turbo-duration',m).disabled=!!active;const area=$('#lw-turbo-status',m);area.innerHTML=job?`<h3>${esc(({running:'Turbo is running',cancelling:'Stopping at the saved clock',completed:'Turbo complete',cancelled:'Turbo stopped',failed:'Turbo stopped after an error',interrupted:'Server was restarted'})[job.status]||job.status)}</h3><progress style="width:100%" max="${job.minutes}" value="${job.completed}" aria-label="Saved simulation minutes"></progress><p>${job.completed.toLocaleString()} / ${job.minutes.toLocaleString()} minutes saved · elapsed ${turboDuration(job.elapsedMs)}${job.estimatedRemainingMs!=null?' · estimated remaining '+turboDuration(job.estimatedRemainingMs):''}</p>${job.error?'<p>'+esc(job.error)+'</p>':''}${active?'<button class="btn btn-soft" id="lw-turbo-stop">Stop Turbo</button>':'<button class="btn btn-teal" id="lw-turbo-return">View the updated scene</button>'}`:'';const stop=$('#lw-turbo-stop',m);if(stop)stop.onclick=async()=>{stop.disabled=true;display((await api(url,{method:'DELETE'})).job);};const back=$('#lw-turbo-return',m);if(back)back.onclick=async()=>{m.remove();if(S.world===world){S.worldData=null;stageState.justAdvanced=false;if(location.hash===`#/stage?w=${world}`)await stageScreen();else nav(`#/stage?w=${world}`);}};return active;};
 const poll=async()=>{if(!m.isConnected)return;try{const {job}=await api(url);if(m.isConnected){display(job);timer=setTimeout(poll,1200);}}catch(error){if(m.isConnected)fail(error);}};
 $('#lw-turbo-start',m).onclick=async()=>{const button=$('#lw-turbo-start',m);button.disabled=true;try{stopNarration();const {job}=await api(url,{method:'POST',body:{minutes:Number($('#lw-turbo-duration',m).value)}});display(job);const root=document.querySelector(".lw-anchor-nav");if(root)livingTurboBadge(root);}catch(e){button.disabled=false;fail(e);}};await poll();
}
async function livingTurboBadge(root){const world=S.world;const refresh=async()=>{if(!root.isConnected||S.world!==world)return;try{const {job}=await api(`/api/living/worlds/${world}/turbo`);if(!root.isConnected)return;const active=job&&['running','cancelling'].includes(job.status),button=$('#lw-turbo',root);if(button){button.textContent=active?'Turbo · '+Math.floor(100*job.completed/job.minutes)+'%':'Turbo';button.classList.toggle('active',!!active);}const advance=$('#advance');if(advance&&!stageState.advanceAbort)advance.disabled=!!active;if(active)setTimeout(refresh,2000);}catch{}};await refresh();}
