/* A bounded personal relationship graph. Every resident can become its center. */
'use strict';
const livingRelationNames={Partner:'Partnerschaft',Family:'Familie',Friend:'Freundschaft',Neighbor:'Nachbarschaft',Coworker:'Arbeitskontakt',Classmate:'Schulfreundschaft',Acquaintance:'Bekanntschaft'};
const livingRelationLabel=r=>(r.labels||r.background?.contexts||[r.background?.label||r.kind||'Bekanntschaft']).map(k=>getLang()==='en'?livingEnglishLabel(livingRelationNames[k]||k):livingRelationNames[k]||k).join(' · ');
async function livingBondsScreen(){
 const worldId=S.world,requested=new URLSearchParams(location.hash.split('?')[1]||'').get('sim');
 app.innerHTML=chrome('bonds',{worldTitle:'Beziehungsnetz',sub:'Sims und ihre persönlichen Verbindungen'})+`<main class="lw-bonds"><div class="lw-world-heading"><div><p class="eyebrow">MENSCHEN & VERBINDUNGEN</p><h1>Beziehungsnetz</h1><p>Ein Klick auf eine Figur macht sie zum Mittelpunkt. Jeder Sim ist auswählbar.</p></div><button class="btn btn-teal" id="lw-bond-sim">Sim wählen</button></div><div class="lw-bond-layout"><section class="lw-bond-board"><div class="lw-bond-tools"><button class="btn btn-soft small" id="lw-bond-back">← Zurück</button><button class="btn btn-soft small" id="lw-bond-fit">Übersicht</button><button class="btn btn-soft small" id="lw-bond-minus" aria-label="Graph verkleinern">−</button><button class="btn btn-soft small" id="lw-bond-plus" aria-label="Graph vergrößern">+</button><button class="btn btn-soft small" id="lw-bond-hand" aria-pressed="false">✋ Verschieben</button><label><input id="lw-bond-only-anchors" type="checkbox"> Kontakte mit Anker</label></div><div class="lw-bond-canvas" id="lw-bond-canvas"><svg id="lw-bond-svg" aria-label="Persönlicher Beziehungsgraph"><defs></defs><g></g></svg></div><div class="lw-bond-footer"><span id="lw-bond-count"></span><button class="btn btn-soft small" id="lw-bond-prev">← Kontakte</button><button class="btn btn-soft small" id="lw-bond-next">Kontakte →</button></div></section><aside class="lw-bond-sidebar"><div id="lw-bond-current"></div><div id="lw-bond-detail"></div><h3>⚓ Verankerte Sims</h3><input id="lw-bond-anchor-search" placeholder="Anker nach Namen suchen" aria-label="Verankerte Sims suchen"><div id="lw-bond-anchors"></div><div class="lw-pages"><button class="btn btn-soft small" id="lw-bond-anchor-prev">←</button><span id="lw-bond-anchor-count"></span><button class="btn btn-soft small" id="lw-bond-anchor-next">→</button></div><button class="btn btn-soft" id="lw-bond-all">Alle Sims durchsuchen</button></aside></div></main>`;
 bindChrome();const canvas=$('#lw-bond-canvas'),svg=$('#lw-bond-svg'),vp=$('g',svg),lifeEvents=new AbortController();const pageSize=8;let centerId=requested,offset=0,anchorOffset=0,token=0,controller,fitScale=1,hand=false;
 const valid=()=>canvas.isConnected&&S.world===worldId;
 const focus=id=>livingBondsJump(id),pick=()=>livingSimPicker(s=>focus(s.id));$('#lw-bond-sim').onclick=pick;$('#lw-bond-all').onclick=pick;$('#lw-bond-back').onclick=()=>history.back();
 const setHand=enabled=>{hand=enabled;controller?.setEnabled(enabled);$('#lw-bond-hand').setAttribute('aria-pressed',String(enabled));$('#lw-bond-hand').textContent=enabled?'✋ Verschieben · an':'✋ Verschieben';};
 $('#lw-bond-hand').onclick=()=>setHand(!hand);window.addEventListener('keydown',e=>{if(e.key==='Escape'&&valid())setHand(false);},{signal:lifeEvents.signal});
 $('#lw-bond-plus').onclick=()=>controller?.zoom(1.2);$('#lw-bond-minus').onclick=()=>controller?.zoom(1/1.2);
 const fit=()=>{controller?.dispose();const radius=Number(svg.dataset.radius)||350;fitScale=Math.min(1.05,Math.max(.18,Math.min(canvas.clientWidth,canvas.clientHeight)/(radius*2)));controller=panZoom(canvas,vp,{x:canvas.clientWidth/2,y:canvas.clientHeight/2,scale:fitScale,enabled:hand});};$('#lw-bond-fit').onclick=fit;
 const portrait=(p,r,x=0,y=0)=>p.asset_id?`<image href="/api/living/library/${encodeURIComponent(p.portrait_asset_id||p.asset_id)}?variant=sprite" x="${x-r}" y="${y-r}" width="${r*2}" height="${r*2}" preserveAspectRatio="xMidYMin slice" clip-path="url(#bond-${p.id})"/>`:`<text x="${x}" y="${y+7}" class="lw-bond-symbol">◇</text>`;
 const details=(p,r)=>{const target=$('#lw-bond-detail');target.innerHTML=`<h3 data-no-translate>${esc(p.name)}</h3><p>${esc(livingPreviewSummary(p))}</p><p>${esc(livingRelationLabel(r))}</p><p>Nähe ${Math.round((r.closeness||0)*100)}% · Vertrauen ${Math.round((r.trust||0)*100)}% · Spannung ${Math.round((r.tension||0)*100)}%</p>${r.background?`<p>${esc(r.background.sharedHistory||'')}</p><small>${esc(r.background.thread||'')} · Ausgangshintergrund</small>`:''}<button class="btn btn-teal small" data-focus-person>Als Mittelpunkt öffnen</button>`;$('[data-focus-person]',target).onclick=()=>focus(p.id);};
 const show=async()=>{
  const current=++token;const r=await api(`/api/living/worlds/${worldId}/sims/${centerId}/relations?`+new URLSearchParams({offset:String(offset),limit:String(pageSize),anchored:$('#lw-bond-only-anchors').checked?'1':''}));if(!valid()||current!==token)return;
  const c=r.center,neighbors=r.neighbors,nodes=[c,...neighbors],positions=new Map([[c.id,{x:0,y:0,r:58}]]);
  neighbors.forEach((p,i)=>{const first=Math.min(10,neighbors.length),outer=i>=first,total=outer?neighbors.length-first:first,index=outer?i-first:i,angle=index*2*Math.PI/Math.max(1,total)-Math.PI/2,radius=outer?460:250;positions.set(p.id,{x:Math.cos(angle)*radius,y:Math.sin(angle)*radius,r:42});});
  svg.dataset.radius=neighbors.length>10?'565':'405';$('defs',svg).innerHTML=nodes.map(p=>{const at=positions.get(p.id);return `<clipPath id="bond-${p.id}"><circle cx="${at.x}" cy="${at.y}" r="${at.r-4}"/></clipPath>`;}).join('');
  vp.innerHTML=neighbors.map(p=>{const at=positions.get(p.id),r=p.relation;return `<path class="lw-bond-edge ${p.anchored?'anchored':''}" data-relationship="${p.id}" d="M0 0 L${at.x} ${at.y}" style="stroke-width:${1.5+(r.closeness||0)*3}"><title>${esc(c.name+' ↔ '+p.name+' · '+livingRelationLabel(r))}</title></path>`;}).join('')+neighbors.map(p=>{const at=positions.get(p.id),full=livingRelationLabel(p.relation),words=full.split(' '),lines=[];let line='';for(const word of words){if(line&&line.length+word.length+1>20){lines.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)lines.push(line);const visible=lines.slice(0,3);if(lines.length>3)visible[2]+=' …';const width=Math.max(60,...visible.map(t=>t.length*7+16)),height=visible.length*16+10;let angle=Math.atan2(at.y,at.x)*180/Math.PI;if(angle>90||angle< -90)angle+=180;if(Math.abs(at.x)<80)angle=0;return `<g class="lw-bond-edge-label" data-relationship="${p.id}" role="button" tabindex="0" aria-label="${esc(p.name+' · '+full)}" transform="translate(${at.x*.5+(Math.abs(at.x)<80&&at.y<0?85:0)},${at.y*.5}) rotate(${angle})"><title>${esc(p.name+' in relation to '+c.name+': '+full)}</title><rect x="${-width/2}" y="${-height/2}" width="${width}" height="${height}" rx="9"/>${visible.map((line,i)=>`<text x="0" y="${-(visible.length-1)*8+5+i*16}">${esc(line)}</text>`).join('')}</g>`;}).join('')+nodes.map(p=>{const at=positions.get(p.id),central=p.id===c.id,n=p.name.lastIndexOf(' '),first=n>0?p.name.slice(0,n):p.name,last=n>0?p.name.slice(n+1):'',textTop=central?-142:at.y< -100?at.y-at.r-92:at.y+at.r+22,job=p.activityStatus?.label||'Not recorded',words=job.split(' '),jobLines=[''];for(const word of words){const k=jobLines.length-1;if(jobLines[k].length+word.length>24&&jobLines[k])jobLines.push(word);else jobLines[k]+=(jobLines[k]?' ':'')+word;}return `<g class="lnode lw-bond-node ${central?'central':''} ${p.anchored?'anchored':''}" data-bond-sim="${p.id}" role="button" tabindex="0" aria-label="${esc(p.name)} · focus this Sim"><title>${esc(p.name+' · '+livingPreviewSummary(p))} · ${p.anchored?'⚓ Anchored':'Procedural'} · ${esc(p.locationSummary)}</title><circle class="lw-bond-ring" cx="${at.x}" cy="${at.y}" r="${at.r}" style="--sim-colour:${esc(p.colour)}"/>${portrait(p,at.r-4,at.x,at.y)}<text class="lw-bond-name" x="${at.x}" y="${textTop}">${esc(first)}</text><text class="lw-bond-name" x="${at.x}" y="${textTop+18}">${esc(last)}</text><text class="lw-bond-meta" x="${at.x}" y="${textTop+40}">${p.age} ${getLang()==='en'?'years':'Jahre'}</text>${jobLines.slice(0,2).map((text,i)=>`<text class="lw-bond-meta" x="${at.x}" y="${textTop+60+i*18}">${esc(text)}</text>`).join('')}${p.anchored?`<g class="lw-bond-anchor" transform="translate(${at.x+at.r*.7},${at.y-at.r*.7})"><circle r="14"/><text y="5">⚓</text></g>`:''}${central?`<text class="lw-bond-central" x="0" y="-168">MITTELPUNKT</text>`:''}</g>`;}).join('');
  $$('[data-bond-sim]',vp).forEach(el=>{el.onclick=()=>{if(!controller?.wasDragged())focus(el.dataset.bondSim);};el.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();focus(el.dataset.bondSim);}};});$$('[data-relationship]',vp).forEach(el=>{const inspect=e=>{e.stopPropagation();if(controller?.wasDragged())return;const p=neighbors.find(p=>p.id===el.dataset.relationship);details(p,p.relation);};el.onclick=inspect;el.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();inspect(e);}};});
  const panel=$('#lw-bond-current');panel.innerHTML=`<p class="eyebrow">MITTELPUNKT</p><h2 data-no-translate id="lw-bond-center" data-sim="${c.id}">${esc(c.name)}</h2><p>${esc(livingPreviewSummary(c))} · ${c.anchored?'⚓ verankert':'prozedural'}</p><p>${esc(c.locationSummary)}</p><div class="lw-resident-actions"><button data-bond-play>▶ Play</button><button data-bond-world>◎ Welt</button><button data-bond-profile>Profil</button></div>`;$('[data-bond-play]',panel).onclick=()=>livingJump(c.target);$('[data-bond-world]',panel).onclick=()=>livingWorldJump(c.id);$('[data-bond-profile]',panel).onclick=()=>livingProfileDrawer(c.id);$('#lw-bond-detail').innerHTML='';
  $('#lw-bond-count').textContent=r.total?`${offset+1}–${Math.min(offset+pageSize,r.total)} / ${r.total} Kontakte`:'Noch keine Kontakte in dieser Auswahl';$('#lw-bond-prev').disabled=!offset;$('#lw-bond-next').disabled=offset+pageSize>=r.total;fit();
 };
 $('#lw-bond-only-anchors').onchange=()=>{offset=0;show().catch(fail);};$('#lw-bond-prev').onclick=()=>{offset=Math.max(0,offset-pageSize);show().catch(fail);};$('#lw-bond-next').onclick=()=>{offset+=pageSize;show().catch(fail);};
 const anchors=async()=>{const r=await api(`/api/living/worlds/${worldId}/sims?`+new URLSearchParams({limit:'6',offset:String(anchorOffset),anchored:'1',search:$('#lw-bond-anchor-search').value}));if(!valid())return;$('#lw-bond-anchors').innerHTML=r.sims.map(p=>`<button class="lw-bond-anchor-person" data-anchor-center="${p.id}">${p.asset_id?`<img src="/api/living/library/${encodeURIComponent(p.portrait_asset_id||p.asset_id)}?variant=sprite" alt="">`:'<span>◇</span>'}<span><b data-no-translate>${esc(p.name)}</b><small>${esc(livingPreviewSummary(p))}</small><small>${esc(p.locationSummary)}</small></span></button>`).join('')||'<p>Keine Anker gefunden. Alle Sims lassen sich über „Sim wählen“ öffnen.</p>';$('#lw-bond-anchor-count').textContent=r.total?`${anchorOffset+1}–${Math.min(anchorOffset+6,r.total)} / ${r.total}`:'0';$('#lw-bond-anchor-prev').disabled=!anchorOffset;$('#lw-bond-anchor-next').disabled=anchorOffset+6>=r.total;$$('[data-anchor-center]').forEach(el=>el.onclick=()=>focus(el.dataset.anchorCenter));};
 let timer;$('#lw-bond-anchor-search').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{anchorOffset=0;anchors().catch(fail);},180);};$('#lw-bond-anchor-prev').onclick=()=>{anchorOffset=Math.max(0,anchorOffset-6);anchors().catch(fail);};$('#lw-bond-anchor-next').onclick=()=>{anchorOffset+=6;anchors().catch(fail);};
 if(!centerId){let first=await api(`/api/living/worlds/${worldId}/sims?limit=1&anchored=1`);if(!first.sims.length)first=await api(`/api/living/worlds/${worldId}/sims?limit=1`);centerId=first.sims[0]?.id;}
 if(centerId)await show();await anchors();
 const observer=new ResizeObserver(()=>{if(!valid()){observer.disconnect();controller?.dispose();lifeEvents.abort();clearTimeout(timer);}else if(controller)fit();});observer.observe(canvas);
}
